### PR TITLE
Remove TODOs for secp256k1 callbacks

### PR DESCRIPTION
**Pull request by real-or-random**
These TODOs have been solved in https://github.com/rust-bitcoin/rust-secp256k1/pull/115.

### CODE REVIEW

**Comment by elichai** [comment]
Well technically it's not exactly the same (these TODOs talk about runtime setting) but in practice we don't want to let users set these callbacks so setting them at compile time achieves those TODOs goal.
ACK https://github.com/rust-bitcoin/rust-secp256k1/pull/143/commits/e54233b06e9ed03a0e46d6e514aba5955caea245

**Comment by real-or-random** [comment]
Oh, you're right, it's not my day ... 

But I think I agree, we just don't want to provide the callback setters. So I'll update the commit message here (and that whitespace change that the GitHub editor introduced...)

**Comment by apoelstra** [comment]
Heh, yeah, I'm fine removing "TODO do this, except I don't want to and I won't do it".

**Comment by elichai** [comment]
Rebasing to include #148 should hopefully solve the CI problems

**Comment by real-or-random** [comment]
* rebased on master,
 * updated the commit message
 * and kept the whitespace change (we should have a linebreak at the end of the file)

So this is ready for review.

**Comment by jonasnick** [comment]
Can't merge because travis is still shown as pending.

**Pull request merged**
