### PR TITLE
Disable re-randomization under more conditions

### LINKED ISSUE #470: Problem at use secp256k1 0.22.1 with wasm
Describe the bug
I have the error that i describe later with last release of rust-bitcoin ( no problem with previous versions).

Build environment

OS+version: 20.04.01
Rust/Cargo version: 1.61.0
Rust/Cargo target: wasm32-unknown-unknown

That's the error:
```
Uncaught (in promise) RuntimeError: unreachable
at __rust_start_panic (67d29ce8a8f7d806078e.module.wasm:0xc6d5d8)
at rust_panic (67d29ce8a8f7d806078e.module.wasm:0xc55f4c)
at std::panicking::rust_panic_with_hook::he2a025723e105e28 (67d29ce8a8f7d806078e.module.wasm:0x960d29)
at std::panicking::begin_panic_handler::{{closure}}::hd9f8c213ec91b9d5 (67d29ce8a8f7d806078e.module.wasm:0xa6ac56)
at std::sys_common::backtrace::__rust_end_short_backtrace::h6efd730283875809 (67d29ce8a8f7d806078e.module.wasm:0xc6c185)
at rust_begin_unwind (67d29ce8a8f7d806078e.module.wasm:0xc16d18)
at core::panicking::panic_fmt::hb02133958c1e7d35 (67d29ce8a8f7d806078e.module.wasm:0xc24531)
at rand::rngs:thread:THREAD_RNG_KEY::__init::{{closure}}::ha2ad45ff6630e75f (67d29ce8a8f7d806078e.module.wasm:0xa55aef)
at core::result::Result<T,E>::unwrap_or_else::hdc727ae752f97c76 (67d29ce8a8f7d806078e.module.wasm:0x73eae4)
at rand::rngs:thread:THREAD_RNG_KEY::__init::hfb75fbbba2c214fb (67d29ce8a8f7d806078e.module.wasm:0x80efe3)
```

If anyone wants to repro, check out this commit:
https://github.com/diba-io/bitmask-core/commit/76e83c953b0c7ecd5006b1c9d32c01e4cb644c6d

### PR DESCRIPTION
**Pull request by apoelstra**
Fixes #470

### CODE REVIEW

**Comment by apoelstra** [comment]
cc @Kixunil @elichai @real-or-random

**Review by Kixunil — APPROVED** [review]
ACK d206891eaaaee32e1b982f6d1439a3e19d0ebfe8

**Review by tcharding — APPROVED** [review]
ACK d206891eaaaee32e1b982f6d1439a3e19d0ebfe8

**Comment by apoelstra** [comment]
Thanks both of you! I need an ack from @TheBlueMatt or @elichai to merge.

**Comment by elichai** [comment]
Isn't this just "solved" by not enabling `rand-std`?

**Comment by apoelstra** [comment]
@elichai rust-bitcoin enables `rand-std`, so if you use rust-bitcoin then this feature is on.

We could probably soften that, or at least make it optional, in rust-bitcoin ... but it will remain the case that if anything in your dep tree turns on `rand-std` there's no way to turn it off. (Also, `rand-std` provides useful functionality that wasm people may want.)

**Comment by apoelstra** [comment]
@sanket1729 I have made you a maintainer of this project. Could you ACK this so we can get this out before #475?

Unless @elichai has an objection.

**Comment by tcharding** [comment]
Do we want the version bump to 0.23.4 if we are going to merge #475 straight away and bump to 0.24.0?

**Review by sanket1729 — APPROVED** [review]
ACK d206891eaaaee32e1b982f6d1439a3e19d0ebfe8

**Comment by apoelstra** [comment]
@tcharding yes, we absolutely want this in a minor version bump.

**Comment by tcharding** [comment]
@sanket just answered me over here: https://github.com/rust-bitcoin/rust-secp256k1/pull/475#issuecomment-1189593726

Thanks!

**Comment by apoelstra** [comment]
Correct!

**Pull request merged**
