### PR TITLE
Update changelog for v0.17.0

### PR DESCRIPTION
**Pull request by stevenroose**

### CODE REVIEW

**Comment by elichai** [comment]
Maybe wait and add the ECDH PR if it will get merged :)

**Comment by stevenroose** [comment]
Cool. I'll check tomorrow if there was progress. :)

**Comment by apoelstra** [comment]
Can you add a note now that #180 is in, and also add a commit that bumps the version number?

**Comment by stevenroose** [comment]
Added and the version was already bumped in the -sys PR.

**Pull request merged**
