### PR TITLE
attempt to fix docs.rs docs

### PR DESCRIPTION
**Pull request by apoelstra**

### CODE REVIEW

**Comment by mpapierski** [comment]
+1. It would be very useful to access docs.rs again for this project.

**Comment by apoelstra** [comment]
@TheBlueMatt can we just merge this? It doesn't make anything worse, at least.

**Comment by apoelstra** [comment]
Great, will release a new minor version with it.

**Comment by apoelstra** [comment]
Great, will release a new minor version with it.

**Comment by stevenroose** [comment]
Ah, doesn't seem like this version got pushed, is that possible?

**Comment by apoelstra** [comment]
Yes, when https://github.com/rust-bitcoin/rust-secp256k1/pull/72 is merged.

**Comment by stevenroose** [comment]
Oh. Yeah I can't give approvals since I'm not part of the org :D

**Pull request merged**
