### PR TITLE
Update vendored lib secp256k1 to v0.4.0

### PR DESCRIPTION
**Pull request by Davidson-Souza**
Replaces  #645 and #652. Precedes #627. 

I'm basically using #652 but resolving the linking problems,

My local CI is erring on windows cross-test, but I can compile without issue with `cargo build --target x86_64-pc-windows-gnu`. Some MIPS jobs failed before even installing cross, I think those aren't really related to this PR. Any ideas on what can be happening?

### CODE REVIEW

**Comment by apoelstra** [comment]
Hmm, not sure what to make of this CI failure. Will try kicking it tomorrow.

**Comment by apoelstra** [comment]
ACK 102df632b3b75dfba9af1f39653548c7fb9486bd. I have a small preference that the last two commits be squashed (so that each one can be tested using the committed libsecp and the committed patchfiles).

Will ACK for real once we sort out CI.

**Comment by Davidson-Souza** [comment]
Regarding the MIPS CI, I think it's the same as https://github.com/rust-lang/rust/issues/115218.

**Comment by Davidson-Souza** [comment]
Pushed [dccaf41](https://github.com/rust-bitcoin/rust-secp256k1/commit/dccaf4135330585f65b16e1e99a2bf0e7c5d6599) I've fixed windows cross compiling error and squashed the last two commits.

MIPS* will likely only be solved by removing MIPS at all, because it is now tier 3. Or making another job that builds with `cargo +nightly build -Z build-std`

**Comment by apoelstra** [comment]
Ok, concept ACK from me just removing MIPs then from our tests :/.

**Comment by apoelstra** [comment]
In 199d27cea32203b224b208627533c2e813cd3b21:

You have not updated the version in secp256k1-sys/Cargo.toml to match the version put in the vendored symbols.

**Comment by Davidson-Souza** [comment]
CI is working now. 

> You have not updated the version in secp256k1-sys/Cargo.toml to match the version put in the vendored symbols.

Wait, [ac6d106](https://github.com/rust-bitcoin/rust-secp256k1/pull/653/commits/ac6d1063013067d7277f2cfe1235ef80249d1b4d) bumps secp256k1-sys to `0.9.0`, that's the version used for renaming. Do you want them to be squashed?

**Comment by apoelstra** [comment]
Ah, yes, I was reading my diff backward.

Yes, please squash them -- that way when I run the revendoring script on each commit, I get a clean diff.

**Comment by tcharding** [comment]
I'm confused; how did you fix the linking errors I was getting if there are no additional changes other than the MIPs stuff?

**Comment by Davidson-Souza** [comment]
@apoelstra 
> Yes, please squash them -- that way when I run the revendoring script on each commit, I get a clean diff.

I think it's everything ok now.

@tcharding 
> I'm confused; how did you fix the linking errors I was getting if there are no additional changes other than the MIPs stuff?

I've updated some patch files, but I squashed it as suggested [here](https://github.com/rust-bitcoin/rust-secp256k1/pull/653#issuecomment-1732366791)

**Comment by tcharding** [comment]
> > I'm confused; how did you fix the linking errors I was getting if there are no additional changes other than the MIPs stuff?
> 
> I've updated some patch files, but I squashed it as suggested [here](https://github.com/rust-bitcoin/rust-secp256k1/pull/653#issuecomment-1732366791)

Interesting, so the changes are fine (clearly since CI runs), the bit that I'm confused by is that `git` says the patches are created by myself and @apoelstra, I thought that when one edited patches that the patch was author change - that is what confused me.

**Review by tcharding — APPROVED** [review]
ACK 3f5b6d3c587ed1a83ca1c4fa37f08a02545ad294

**Comment by tcharding** [comment]
I reviewed all the changes to files outside of `depend`, relying on @apoelstra running the vendor script to check that the changes were made mechanically.

**Comment by apoelstra** [comment]
In 3f5b6d3c587ed1a83ca1c4fa37f08a02545ad294 the patchfiles are still updated in their own commit, meaning that the last several commits do not pass tests for me, since the vendored code does not match the output of the vendoring script. Can you squash the patchfile commit into the one that changes the vendored files?

**Comment by Davidson-Souza** [comment]
I think they are all in the same commit now.

Sorry for the delay, I was traveling back from Azores.

**Review by tcharding — APPROVED** [review]
ACK 3f5b6d3c587ed1a83ca1c4fa37f08a02545ad294

**Comment by tcharding** [comment]
3 hours to run CI is a fair bit, is that expected?

**Comment by sanket1729** [comment]
Restarted the jobs. Maybe a Github UI issue.

**Comment by apoelstra** [comment]
@Davidson-Souza 1639f25f039db525e8de9a29530e1f7d6402dbd0 is still its own commit.

**Comment by Davidson-Souza** [comment]
Oh, sorry! I've pushed the wrong branch. Now it's squashed.

**Review by tcharding — APPROVED** [review]
ACK be48b75e2a66edb1e61b31cc05ec7f05383e4140

**Comment by apoelstra** [comment]
I'm sorry to keep doing this to you, but could you

*  drop 3726473f4125f8110e1b999ad2f1db551a7bb723? I know this is my commit but it does appear to break my local CI script. It will cause a merge conflict when rebasing ("both sides added something.orig") and you can resolve the conflict by just taking your version.
* Update the Cargo-minimal.lock and Cargo-recent.lock files. (I think an old version of this PR did do this.)

The former I could probably just patch my local checks to be more forgiving, but the latter is needed before I can merge this.

**Comment by Davidson-Souza** [comment]
@apoelstra 
> drop https://github.com/rust-bitcoin/rust-secp256k1/commit/3726473f4125f8110e1b999ad2f1db551a7bb723? I know this is my > commit but it does appear to break my local CI script. It will cause a merge conflict when rebasing ("both sides added something.orig") and you can resolve the conflict by just taking your version.
>
> Update the Cargo-minimal.lock and Cargo-recent.lock files. (I think an old version of this PR did do this.)

Done!

**Comment by apoelstra** [comment]
Ok, great :) I am still getting errors related to .orig files but I'll just patch my script to ignore those. I think we can finally merge this!

Thanks so much for keeping with this despite so many iterations that were purely about making our CI machine happy. (Though FWIW we do get a lot of value in being able to machine-check that the vendored code is consistent.)

**Review by apoelstra — APPROVED** [review]
ACK 80b2a8d4aa6ffa72041d569eab2278cd8c1ace2a

**Pull request merged**
