### PR TITLE
Upgrade the vendored `libsecp256k1` code to v0.2.0

### PR DESCRIPTION
**Pull request by tcharding**
This bumps `secp256k1` to v0.26.0 and `secp256k1-sys` to v0.8.0

`libsecp256k1` v0.2.0 was just released.

Update the vendored code using

 `./vendor-libsecp.sh depend 0_8_0 21ffe4b`

```
git show 21ffe4b
commit 21ffe4b22a9683cf24ae0763359e401d1284cc7a (tag: v0.2.0)
Merge: 8c949f5 e025ccd
Author: Pieter Wuille <pieter@wuille.net>
Date:   Mon Dec 12 17:00:52 2022 -0500

    Merge bitcoin-core/secp256k1#1055: Prepare initial release

    e025ccdf7473702a76bb13d763dc096548ffefba release: prepare for initial release 0.2.0 (Jonas Nick)
    6d1784a2e2c1c5a8d89ffb08a7f76fa15e84fff5 build: add missing files to EXTRA_DIST (Jonas Nick)
    13bf1b6b324f2ed1c1fb4c8d17a4febd3556839e changelog: make order of change types match keepachangelog.com (Jonas Nick)
    b1f992a552785395d2e60b10862626fd11f66f84 doc: improve release process (Jonas Nick)
    ad39e2dc417f85c1577a6a6a9c519f5c60453def build: change package version to 0.1.0-dev (Jonas Nick)
    90618e9263ebc2a0d73d487d6d94fd3af96b973c doc: move CHANGELOG from doc/ to root directory (Jonas Nick)

    Pull request description:

      Based on #964

    ACKs for top commit:
      sipa:
        ACK e025ccdf7473702a76bb13d763dc096548ffefba

    Tree-SHA512: b9ab71d7362537d383a32b5e321ef44069f00e3e92340375bcd662267bc5a60c2bad60222998e6602cfac24ad65efb23d772eac37c86065036b90ef090b54c49
```

Requires a new version of `secp256k1-sys`, use v0.8.0

- Update the `secp256k1-sys` manifest (including links field)
- Update symbols to use 0_8_0
- Add a changelog entry
- depend on the new version in `secp256k1`

Which in turn requires a new version of `secp256k1`, use v0.26.0

### CODE REVIEW

**Comment by tcharding** [comment]
Hope I'm not stealing anyones thunder here, I gave you guys a day or two to do it :)

**Comment by elichai** [comment]
I think the `scratch_impl.h.patch` is outdated or something, because it seems that the `malloc` and `free` calls are still there

**Comment by apoelstra** [comment]
Nice, thanks!! You're not stepping on my thunder -- but yeah, it looks like me (or one of the folks involved with the vendoring patch stuff) will have to dig into it.

**Comment by tcharding** [comment]
Ah cheers, that's enough info for me to have another play with it. But by all means don't let me hold you back :)

**Comment by tcharding** [comment]
ok, that took an embarrassingly long time to figure out. I just had to work out how to modify one of the patch files to resemble the code in v0.2.0 - see patch 1 of the PR.

**Comment by apoelstra** [comment]
Lol, we should really document how to generate these patch files ... IIRC I've done it twice, but several times I've just edited the patchfiles directly in vim.

**Comment by apoelstra** [comment]
The commit message shows an old commit ID; it should be 9a8d65f07f171b07bd7a33828dce073d819fbdef.

Otherwise looks good, ACK!

**Comment by tcharding** [comment]
> Lol, we should really document how to generate these patch files ... IIRC I've done it twice, but several times I've just edited the patchfiles directly in vim.

It was obvious what needed doing, I just never use `patch` because I always use `git` so I kept messing it up - also I was up all night loosing money on France :)

**Comment by tcharding** [comment]
> The commit message shows an old commit ID; it should be 9a8d65f07f171b07bd7a33828dce073d819fbdef.

Are you sure, I used the tagged commit. Isn't `02ebc29 release cleanup: bump version after 0.2.0` post release changes?

**Comment by apoelstra** [comment]
Yeah, the ID in your commit message would've made more sense, but the one you actually used, according to `depend/secp256k1-HEAD-revision.txt`, was `9a8d65f07f171b07bd7a33828dce073d819fbdef`.

I would accept either one, but right now they're not consistent.

**Comment by tcharding** [comment]
Oh I see what you mean, thanks. I must have botched the `./vendor-libsecp.sh` command at some stage by omitting the commit id.

Fixed now.

**Comment by apoelstra** [comment]
Looks like you swapped the commit ID and the version # in the script :)

**Comment by tcharding** [comment]
Might have been quicker for you to do this one yourself :)

**Pull request merged**
