### PR TITLE
Bump version to 0.23.2

### PR DESCRIPTION
**Pull request by vorot93**

### CODE REVIEW

**Review by apoelstra — APPROVED** [review]
ACK 141f2d1dbcf52ea72bcd0d69020a0ba028768f82

**Comment by tcharding** [comment]
Tagging doesn't seemed to have worked on this release either @apoelstra
```
$ git fetch --all --tags; git tag | grep secp256k1-0.23
Fetching origin
Fetching upstream
secp256k1-0.23.0
secp256k1-0.23.1
```

**Comment by apoelstra** [comment]
Ah, I see, `git push --tags` on this repo just sends stuff to my personal fork.

I will remember to type `git push origin --tags` in the future.

Should be good now.

**Comment by tcharding** [comment]
If your brain works anything like mine you'll forget at least one more time, in these cases I add a shell alias, somehow my brain remembers to use it, I'm not sure why.

**Pull request merged**
