### PR TITLE
Use known endianness when comparing arrays

### PR DESCRIPTION
**Pull request by tcharding**
We cannot guarantee the endianness of our types that use an inner array. When comparing and hashing the inner byte array first convert it to a know endianness. Elect to use little-endian because its more common in today's machines.

Fix: #463

### CODE REVIEW

**Comment by elichai** [comment]
As @apoelstra said, the representation of these types might be more complicated than just reversing them.
also the `Hash` trait doesn't promise portability at all: https://doc.rust-lang.org/std/hash/trait.Hash.html#portability

about `PartialEq/Ord` we probably need to serialize them, I don't see any other way to get consistent result across machines.

(or actually call `secp256k1_ec_pubkey_cmp` for pubkeys, do we do that already?)

**Comment by tcharding** [comment]
Thanks @elichai, I'll put in a bit more effort and re-spin.

**Comment by apoelstra** [comment]
>(or actually call secp256k1_ec_pubkey_cmp for pubkeys, do we do that already?)

We do this for "real" pubkeys but not the ones in secp-sys, I think. We should fix that. People who really want to compare the underlying bytestrings, despite the warnings all over libsecp about this being non-portable and liable to break, can do so by using `.as_bytes`.

**Comment by elichai** [comment]
Maybe the underlying ones just should implement Eq/Ord?

**Comment by apoelstra** [comment]
I believe this is superceded by #506 which calls into the FFI to compare these objects correctly.

**Comment by tcharding** [comment]
> I believe this is superceded by #506 which calls into the FFI to compare these objects correctly.

And its just plain wrong :)

**Comment by tcharding** [comment]
> Maybe the underlying ones just shouldn't implement Eq/Ord?

Would it be worth removing the `Eq`/`Ord` impls like you suggest @elichai and having something like `eq_unstable`?

**Comment by tcharding** [comment]
> We do this for "real" pubkeys but not the ones in secp-sys, I think. We should fix that. People who really want to compare the underlying bytestrings, despite the warnings all over libsecp about this being non-portable and liable to break, can do so by using `.as_bytes`.

You mean by using `underlying_bytes`, right? I ask because I wondered why we did not implement `as_bytes` and `to_bytes`. Also we have `AsRef` and `Index` that give access to the underlying bytes also - do we want these? Or at a minimum do we want to document all of them stating that the bytes cannot be relied upon across versions?

**Pull request closed without merging**
