### PR TITLE
Bump secp256k1-sys version to 0.7.0

### PR DESCRIPTION
**Pull request by tcharding**
We are ready to release a new minor version of `secp256k1-sys`, in order to do so we must make change the symbol names to reflect the new version as well as the usual changelog and version bump.

In preparation for releasing `secp256k1-sys` v0.7.0 do:

- Rename symbols to from `0_6_1` -> `0_7_0`, done mechanically (search and replace)
- Add changes log notes
- Bump `secp256k1-sys` crate version 0.6.1 -> 0.7.0, justified because we have added new public methods to various types (e.g., `PublicKey::cmp_fast_unstable`)

### Notes

I based this PR on:
- https://github.com/rust-bitcoin/rust-secp256k1/pull/490/files
- https://github.com/rust-bitcoin/rust-secp256k1/pull/457/files

### CODE REVIEW

**Comment by tcharding** [comment]
I did#550 so that we can merge this PR, tag and release `secp256k1-sys`, then merge #550 and then tag/release `secp256k1` v0.25.0, keeping the index nice and clean ... I think

**Comment by apoelstra** [comment]
I'm unsure now if we want to hold off on this release until we've dealt with #543 and #546

**Comment by tcharding** [comment]
Lets do them both :)

**Comment by Kixunil** [comment]
Actually, since this bumps `-sys` crate it is unrelated to #543 and may be merged independently. But that one is really close to merging anyway.

**Comment by apoelstra** [comment]
@tcharding ok, now I think this is the only thing blocking release of 0.25.0 :). But it needs rebase.

**Comment by tcharding** [comment]
We have a commit tagged already for secp256k1 v0.25.0 @apoelstra, just mentioning it in case you want to move that tag before releasing.
`ca83f9f (tag: secp256k1-0.25.0) Merge rust-bitcoin/rust-secp256k1#523: Tracking PR for release v0.25.0`

**Review by apoelstra — APPROVED** [review]
ACK 3fa24362723ad6d4694437082300d49d2b4edee3

**Pull request merged**
