### PR TITLE
fix build.rs on Windows

### PR DESCRIPTION
**Pull request by apoelstra**

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
Is there some equivalent warning that will be thrown by msvc if we dont specify a flag?

**Comment by alekseysidorov** [comment]
You can use such method
https://docs.rs/cc/1.0.23/cc/struct.Build.html#method.flag_if_supported

**Comment by TheBlueMatt** [comment]
Needs rebase.

**Comment by apoelstra** [comment]
rebased

**Comment by apoelstra** [comment]
Rebased and used `flag_if_supported`. I think this should be a complete solution; from the `cc` source it looks like it does a trial compilation with every flag that you give to this method and then checks whether stderr is empty.

**Pull request merged**
