### PR TITLE
fix incorrect FFI binding for pubkey_combine

### LINKED ISSUE #669: Incorrect FFI binding for `secp256k1_ec_pubkey_combine`
At least one foreign function declared in Rust seems to be using integer types with a different width than the underlying function definition in C. For example, here’s the declaration of `secp256k1_ec_pubkey_combine` in [secp256k1-sys](https://github.com/rust-bitcoin/rust-secp256k1/tree/master/secp256k1-sys)

```
pub fn secp256k1_ec_pubkey_combine(cx: *const Context,
                                   out: *mut PublicKey,
                                   ins: *const *const PublicKey,
                                   n: c_int)
                                   -> c_int;
```
The parameter `n` is declared to be a 32-bit C integer, but the corresponding C function is expecting a `size_t`, which could be larger depending on the platform:
```
int rustsecp256k1_v0_9_1_ec_pubkey_combine(
	const rustsecp256k1_v0_9_1_context* ctx,
	rustsecp256k1_v0_9_1_pubkey *pubnonce,
	const rustsecp256k1_v0_9_1_pubkey * const *pubnonces,
	size_t n)
```

### PR DESCRIPTION
**Pull request by apoelstra**
Fixes #669.

Needs backport.

### CODE REVIEW

**Comment by tcharding** [comment]
I rekon if we are going to backport this wouldn't it be nicer have a bit more description in the commit log. 

ACK 484e5d8d5b9d001af4ce5796b9837bbc704bebea

**Comment by apoelstra** [comment]
The one line commit log, combined with the one line diff, seem pretty self explanatory to me.

**Review by Kixunil — APPROVED** [review]
ACK 484e5d8d5b9d001af4ce5796b9837bbc704bebea

**Comment by apoelstra** [comment]
Would one or both of you @tcharding @Kixunil like to be a maintainer on this repo?

I think our informal processes are fine to make sure that e.g. crypto stuff doesn't get merged without a crypto person reviewing. There's no reason to use Github to only allow a narrower set of reviewers.

I'll go ahead and merge this with just your ACKs since we're not actually even enforcing the "maintainer must ACK" rule here..

**Comment by apoelstra** [comment]
Lol, oops, I actually screwed up this PR. I updated the secp-sys version but did not re-run the vendoring script to rename all the `0_9_1` functions to `0_9_2`.

**Comment by Kixunil** [comment]
Yeah, I'd like to help maintain this. It's a key piece of the rust-bitcoin infrastructure so being more involved with it should help.

**Review by Kixunil — APPROVED** [review]
ACK 3373cc930eb67559d29eeb65effe0d64dd3e0152

**Comment by apoelstra** [comment]
Thanks! Added you as a maintainer.

**Comment by apoelstra** [comment]
Tagged, published, and yanked previous 0.9.x versions of secp-sys.

**Comment by apoelstra** [comment]
Oops, crap, I need to update rust-secp along with rust-secp-sys, since this was actually a breaking change to rust-secp-sys.

**Comment by tcharding** [comment]
I'm willing to be a maintainer also. I'm not super confident with `unsafe` but willing to invest the time and take the responsibility.

**Comment by apoelstra** [comment]
Bumped you from "Triage" to "Maintain".

**Pull request merged**
