### PR TITLE
increase version to 0.18.0

### PR DESCRIPTION
**Pull request by apoelstra**

### CODE REVIEW

**Review by elichai — APPROVED** [review]
Looks good!

**Comment by real-or-random** [comment]
The compiler paniced, fun. https://travis-ci.org/github/rust-bitcoin/rust-secp256k1/jobs/721505052#L1970
Maybe it's spurious, I'll restart the job.

**Review by real-or-random — APPROVED** [review]

**Comment by elichai** [comment]
Clearing the cache solved this :)

**Review by elichai — APPROVED** [review]

**Comment by elichai** [comment]
I dropped the backtrace commit, because it can slow it down in the future and take more memory (which has a bigger effect on travis I think)

**Comment by real-or-random** [comment]
Oh ok, I assumed it's a good idea anyway but you're right.

**Review by real-or-random — APPROVED** [review]

**Comment by elichai** [comment]
@real-or-random I really hope this is the last time we'll encounter an ICE here. 
If I'm wrong we can set it globally for travis for future difficulties

**Pull request merged**
