### PR TITLE
Derive Hash for Scalar

### PR DESCRIPTION
**Pull request by jirijakes**
Unless there is some safety concern I cannot see, having Scalar implementing Hash would be useful.

### CODE REVIEW

**Comment by Kixunil** [comment]
It has the same security issue as comparison traits which is documented, so this is OK.

**Comment by apoelstra** [comment]
I don't think we need to worry about constant-timeness with `Hash`. Hash functions are typically straight-line code where every operation after the first round is applied to statistically-random data.

**Review by apoelstra — APPROVED** [review]
ACK f87dc911516219641baa604879cfb6016fb35b3c

**Comment by Kixunil** [comment]
@apoelstra this is the non-cryptographic one so I wouldn't bet on it. But again, there's a warning.

**Pull request merged**
