### PR TITLE
Tracking PR for release v0.25.0

### PR DESCRIPTION
**Pull request by tcharding**
Add changelog notes and bump the crate version to v0.25.0!

### CODE REVIEW

**Comment by apoelstra** [comment]
Thanks! I'd like to get #524 in first since it'll improve our docs (and possibly simplify our safety requirements on some functions).

**Comment by tcharding** [comment]
Rebased to pick up #524, no other changes.

**Comment by apoelstra** [comment]
Nice, LGTM. In the next release we'll do all the context-breaking stuff.

**Review by apoelstra — APPROVED** [review]
ACK 1dbd7691da9c829d0474c8582245352f5389375b

**Comment by apoelstra** [comment]
oops @tcharding we need a new (minor) release of secp-sys first, to introduce the new `cmp_fast_unstable` methods.

**Comment by tcharding** [comment]
Did #549 and then did #550 to fix this PR and be the release commit that we tag.

**Pull request merged**
