### PR TITLE
After MSRV bump: Implemented `TryFrom<{u8, i32}>` for `Parity`

### PR DESCRIPTION
**Pull request by Kixunil**

### CODE REVIEW

**Comment by Kixunil** [comment]
Added commit changing `cause()` to `source()`

**Comment by Kixunil** [comment]
Rebased, @tcharding my previous PR had cause->source change so I left it in, do you want me to remove it in favor of your PR?

**Comment by tcharding** [comment]
You were first, leave yours as it is, I'll rebase mine on top of yours.

**Review by tcharding — APPROVED** [review]
ACK df081bede00a61f410f2c2f5aff8ab0e134003f0

**Comment by sanket1729** [comment]
What was the reason that we could not have `Parity::Even` and `Parity::Odd`. Why do we have an i32 wrapping? 

If the underlying FFI guarantees that the value is either 1 or 0. We should represent it in an enum. IMO, there is no need to stick to `i32` just because that's the return type of C code.

**Comment by tcharding** [comment]
Did you get mixed up? We do have an enum
```

/// Represents the parity passed between FFI function calls.
#[derive(Copy, Clone, PartialEq, Eq, Debug, PartialOrd, Ord, Hash)]
pub enum Parity {
    /// Even parity.
    Even = 0,
    /// Odd parity.
    Odd = 1,
}
```
:)

**Review by apoelstra — APPROVED** [review]
ACK df081bede00a61f410f2c2f5aff8ab0e134003f0

**Comment by apoelstra** [comment]
@sanket1729 for the purpose of encoding it in a taproot control block, which requires an integer (a `u1` not an `i32`, but ok)

**Comment by sanket1729** [comment]
Sorry, my local tree was not updated. And I was looking at some old code :(. 

We might not need the TryFrom from `i32`, but I have no complaints about having it either way.

**Comment by Kixunil** [comment]
@sanket1729 FYI my motivation for adding them is based on the [Rust API guidelines](https://rust-lang.github.io/api-guidelines/interoperability.html#conversions-use-the-standard-traits-from-asref-asmut-c-conv-traits) (and I agree with that particular recommendation :))

**Comment by apoelstra** [comment]
@Kixunil for sure -- if we support conversion to/from numerics then we should definitely use `TryFrom` to do it. But I understood Sanket's question as being "why do we support these conversions at all?".

**Pull request merged**
