### PR TITLE
Bump MSRV to 1.48

### PR DESCRIPTION
**Pull request by tcharding**
As per ecosystem wide change, bump the MSRV of both crates to 1.48

Patch 1 is a typo fix to the changelog, I don't see changelogs cached on crates.io in any way so this fix should be able to quietly go in.

Note before this is applied there is no mention of the MSRV in secp256k1-sys, was that intentional? If not, with this applied, we have a mention in the readme.

CI needs some more fixes (wasm job) but because patching CI often leads to me doing 300 pushes I'm leaving it to a separate PR.

### CODE REVIEW

**Review by apoelstra — APPROVED** [review]
ACK 7bba2bc3b5f54e506bf815413660c7d0533dd5e7

**Comment by Kixunil** [comment]
I'm now tempted to rewrite `libsecp256k1` to Rust just to implement `const fn` :laughing:

**Comment by apoelstra** [comment]
So, in seriousness we would like to write some of the "non-crypto" parts of the library in Rust ... in particular serialization and deserialization of keys and signatures. This would let us do a lot of things in rust-bitcoin without ever crossing the FFI boundary, and would let us Miri-test stuff.

Unfortunately this is quite nontrivial because deserialization of compressed points requires doing a square root in the field. And this is sensitive enough that I don't think we could reasonably ask a summer-of-bitcoin student to do it. (Though maybe next year I'll take some time and try to carefully spec out such a project ... along with rewritting the fake-crypto fuzz harness.)

**Comment by Kixunil** [comment]
Could we repurpose some of [my code](https://github.com/Kixunil/toy-secp256k1) for this?

**Comment by apoelstra** [comment]
Yep, maybe -- though it looks like it's dependent on the `bigint` crate for all the hard stuff.

**Pull request merged**
