### PR TITLE
Release 0.21.0

### PR DESCRIPTION
**Pull request by apoelstra**
.

### CODE REVIEW

**Comment by sanket1729** [comment]
This breaks a lot of things downstream. I think it might a good idea to highlight a few of those in release notes. 
Renamed:
1) Moved schnorrsig module to schnorr
2) Moved schnorrsig::PublicKey to XOnlyPublicKey
3) Moved recovery to ecdsa::recovery.

Should I add a warning making these non-breaking changes?

**Comment by apoelstra** [comment]
@sanket1729 you mean, PR to modify the changelog? I can do it.

**Comment by sanket1729** [comment]
@apoelstra , see #348

**Comment by apoelstra** [comment]
Great idea @sanket1729. Merged.

**Comment by sanket1729** [comment]
utACK 8cfd26a210ae7a90b3159af596fb39924984f0f6

**Comment by elichai** [comment]
ACK 8cfd26a210ae7a90b3159af596fb39924984f0f6 Checked the changelog against the git log

**Comment by apoelstra** [comment]
I'd like to get #344 in first actually, it's an API-breaking change but a very minor one.

**Review by sanket1729 — APPROVED** [review]
utACK c3df9b89a2ef57f42f0dffc8e524d9387c3f76a5. Excited for the new release

**Comment by apoelstra** [comment]
@elichai can I get a quick re-ACK and then I'll do it?

**Comment by apoelstra** [comment]
Merged. Published.

Need to push new point release of secp256k1-sys because of #345 ... and actually I think #345 is missing a `pub` qualifier :)

**Comment by sanket1729** [comment]
Might also need a point release for rust-secp. See #360

**Comment by sanket1729** [comment]
> utACK c3df9b8. Excited for the new release

Should have tested with rust-bitcoin before ACKing

**Comment by apoelstra** [comment]
Lol oops. I had also wanted to get #353 in (though less critically). We'll do a point release.

**Pull request merged**
