### PR TITLE
update libsecp, remove endomorphism feature flag and release 0.20.0

### PR DESCRIPTION
**Pull request by apoelstra**

### CODE REVIEW

**Review by sgeisler — DISMISSED** [review]
utACK 833b17601a7f279e64c17c42d96c9a08c0f480ac

To review 8c74e5396cbc03e3f35233227de0df8ca89642ae I just ran the vendoring script and checked for a diff.

**Comment by dr-orlovsky** [comment]
This looks like an important and trivial bugfix which may get merged before this release: https://github.com/rust-bitcoin/rust-secp256k1/pull/266

**Comment by elichai** [comment]
Can you also remove the endianess checks? they aren't needed anymore https://github.com/bitcoin-core/secp256k1/pull/787

**Review by elichai — DISMISSED** [review]
tACK
I tested `rm -rf /depend/secp256k1` and `./vendor-libsecp.sh depend 0_4_0 master` to make sure the results match,

**Review by sgeisler — APPROVED** [review]
utACK c4d2fefa709221f42a808d6c09f579c244d0d68c

**Review by elichai — APPROVED** [review]
tACK, ran the vendoring script on my machine and it produced the same result

**Pull request merged**
