### PR TITLE
Add additional changelog entry

### PR DESCRIPTION
**Pull request by tcharding**
~Bump version to 0.25.1 ready to release~ Add changelog entry for the recently fixed unsoundness issue.

Patch 1 is an annoyingly trivial fix to docs.

### CODE REVIEW

**Comment by apoelstra** [comment]
We never released 0.25.0 so we can just stick with that version number.

**Comment by Kixunil** [comment]
Awesome, so I didn't have to change the report. :D

**Comment by apoelstra** [comment]
@tcharding can you update this PR so it updates the changelog and does nothing else?

**Comment by tcharding** [comment]
Done, thanks for catching my mistake.

**Comment by tcharding** [comment]
> and does nothing else?

I hope patch 1 is ok, its in there so the backports and this all have exactly the same rustdoc code.

**Review by Kixunil — DISMISSED** [review]
ACK a929f287d52bc0763fcab65bb66e30435c878559

(Ignoring that the commit says adding line *before* heading while it should be *after*.)

**Comment by tcharding** [comment]
I fixed the commit message since this repo does not require two acks @apoelstra will be able to merge it still with his ack. Thanks

**Comment by apoelstra** [comment]
@tcharding this commit adds trailing whitespace at the top of the changelog file.

**Comment by apoelstra** [comment]
Also sorry, we have to fix #562 before release.

**Comment by tcharding** [comment]
> @tcharding this commit adds trailing whitespace at the top of the changelog file.

Strange, I wonder why the githook didn't catch this? Even more strange I wonder why I push changes still to this day without reading the diff ...

**Review by apoelstra — APPROVED** [review]
ACK 494b07a415bb3d1a11adbbb82f8f7e31cb4964dc

**Comment by apoelstra** [comment]
Lol, jeez. Since https://github.com/rust-bitcoin/rust-secp256k1/pull/551 we need to do a major rev of secp256k1-sys, and **then** we can release 0.25.0.

**Comment by apoelstra** [comment]
Ah, #549 does this. But it needs a rebase.

**Pull request merged**
