### PR TITLE
update rand to 0.7 and rand_core to 0.5

### PR DESCRIPTION
**Pull request by AxelNennker**
Signed-off-by: Axel Nennker <axel.nennker@telekom.de>

### CODE REVIEW

**Comment by elichai** [comment]
Hi, this violates our policy of MSRV(Minimum Supported Rust Version) of rust 1.22.0.
Thanks for the contribution anyway :)
we're stuck with 0.6 until something will change in that regard.

**Comment by AxelNennker** [comment]
What are the conditions to be met to loosen this requirement?

The Rust ecosystem is moving fast e.g. with async. I think no project can stay behind that. S That would mean a minimum rustc version of 1.39 anyway.

Having old versions of rand means having old versions of rand_core which is a pain.

Please consider upgrading.

⁣Get BlueMail for Android ​

**Comment by elichai** [comment]
@alekseysidorov Please see https://github.com/rust-bitcoin/rust-bitcoin/issues/338


> Having old versions of rand means having old versions of rand_core which is a pain. Please consider upgrading. 

Can you expand on why is it a pain? we re-export our `rand` version so that you can have both rand versions if needed. you can locally import `0.7` but also use `secp256k1::rand` for to pass the right thing to this library.

FYI these problems are because the `rand` ecosystem just loves breaking changes. They already did `rand_core` so I don't get why they keep bumping the major version of that.

**Comment by AxelNennker** [comment]
I want to update https://github.com/hyperledger/ursa/pull/73/files to rand 0.7,
but that doesn't compile because of other dependencies.

So I try to convince the dependencies to upgrade...

'cargo tree -d' shows that Ursa is compiling three different versions of rand_core.

The Ursa group intents to close this PR because they don't see a way to do it.

⁣Get BlueMail for Android ​

**Comment by AxelNennker** [comment]
Found some discussion about the topic here 
https://users.rust-lang.org/t/rust-version-support-in-library-crates-best-practices/4405/28

Rust nursery-crates and other libraries seem to agree on supporting two versions back.

Please consider dropping 
`This library should always compile with any combination of features on Rust 1.22.`

**Comment by elichai** [comment]
> Found some discussion about the topic here
> https://users.rust-lang.org/t/rust-version-support-in-library-crates-best-practices/4405/28
> 
> Rust nursery-crates and other libraries seem to agree on supporting two versions back.
> 
> Please consider dropping
> `This library should always compile with any combination of features on Rust 1.22.`

Well we have actual production requirements. 
production requirements mean:
1. Users can actually compile the code easily(installing only from distribution sources).
2. Reproducibility.

Right now as you said unlike the C++ ecosystem the rust eco-system isn't mature enough to take these production requirements seriously. so we will bump this slowly and hope rust will mature soon(ie having something like `-std=c++11` or https://github.com/rust-lang/rust/issues/65262 ) and that distributions will try and ship compilers faster.

**Comment by AxelNennker** [comment]
Installing rust is really easy https://doc.rust-lang.org/book/ch01-01-installation.html 
and is independent of distributions. 

In our CI we simply use the same mechanism.
https://github.com/hyperledger/indy-sdk/blob/master/libindy/ci/ubuntu.dockerfile#L65
We are doing the CI tests on ubuntu16, windows, ubuntu18, centos with rustc 1.39 following the 'two-version-backward-compatibility' best practice.

So it is really easy to compile and install.

I don't understand the 'Reproducibility' argument. That what Cargo.lock is for, right? If that does not fix Reproducibility then it is a compiler error which rare and usually fixed really fast.

**Comment by TheBlueMatt** [comment]
Last I heard, rustup still downloads binaries from an HTTPS site without even bothering to check any kind of signatures, ie is a really just generally terrible idea to use it if you care about security (eg are handling cryptocurrency).

Even if it were done more carefully, users may not wish to trust a *second* source for binaries which, if compromised, could steal their funds.

Even further, users in production work on building their own rustc/etc to de-risk third party compromise.

For those reasons (not to mention bugs in new features in Rust), we absolutely don’t want to just rely on users having brand-new rustc available.

**Comment by TheBlueMatt** [comment]
Note that the "reproducibility" @elichai mentioned is reproducibility of the whole toolchain all the way to the final binary - having multiple parties build their own rustc (likely via mrustc bootstrap), then have each build the source, and check that, at the end, everyone ended up with the same binary.

Closing for now. If you wish to contribute to the MSRV discussion, please continue that at https://github.com/rust-bitcoin/rust-bitcoin/issues/338

**Comment by real-or-random** [comment]
To save you from looking it up: The MSRV of rand 0.7 is Rust 1.32.

**Pull request closed without merging**
