### PR TITLE
 Implement Ord for arrays

### PR DESCRIPTION
**Pull request by alekseysidorov**
This change allows to use PublicKeys as key in `BTreeMap`.

### CODE REVIEW

**Comment by tamasblummer** [comment]
why would you order public keys like that ?

**Comment by apoelstra** [comment]
We actually do this in Liquid to ensure all our functionaries have a canonical order even if their config files are reordered. Right now we use `serialize_vec` and sort on the vector, since we only do this at startup and we're not worried about the memory.

utACK

**Comment by apoelstra** [comment]
@alekseysidorov can you add a simple test that just compares two nonequal pubkeys, and two equal pubkeys, and ensures that the inequalities in both directions work as expected?

**Comment by apoelstra** [comment]
Sorry, finger slipped, didn't mean to close.

**Comment by alekseysidorov** [comment]
Okay, I have added tests for possible regressions in keys comparison.

**Comment by apoelstra** [comment]
There is no need to instantiate the same key twice, you can just copy the original one. And I meant to check that `<`, `<=`, `>`, `>=` all work correctly for equal and unequal keys. Equality is not affected by this PR.

**Comment by alekseysidorov** [comment]
Something like this?

**Comment by apoelstra** [comment]
Yep, thanks!

**Comment by apoelstra** [comment]
This is actually a bit surprising behavior because it sorts on the internal representation of the public keys, which is essentially the fully serialized x/y coordinates. Users typically see the compressed representation of keys so the order will not appear to be lexicographic.

I don't think this is a big deal - generally people are ordering public keys only to put them in `BTree`s or other sorted data structures; or to get some canonical ordering which isn't too important. And people who really care can always use `PublicKey::serialize` and sort on the output.

**Pull request merged**
