### PR TITLE
secp256k1-sys: update util.h patch to delete more stdio code

### LINKED ISSUE #734: secp256k1-sys cannot be cross compiled using rust cross.
I am trying to cross compile a rust application from Ubuntu to a Windows machine. With podman installed, I run the following: 
`cross build --release --target x86_64-pc-windows-msvc`
Everything is fine, up until the compiler reaches the secp256k1-sys crate.

```
   Compiling same-file v1.0.6
The following warnings were emitted during compilation:

warning: secp256k1-sys@0.10.0: GNU compiler is not supported for this target
warning: secp256k1-sys@0.10.0: GNU compiler is not supported for this target
warning: secp256k1-sys@0.10.0: In file included from /usr/include/stdio.h:894,
warning: secp256k1-sys@0.10.0:                  from depend/secp256k1/src/util.h:14,
warning: secp256k1-sys@0.10.0:                  from depend/secp256k1/src/field.h:10,
warning: secp256k1-sys@0.10.0:                  from depend/secp256k1/src/group.h:10,
warning: secp256k1-sys@0.10.0:                  from depend/secp256k1/src/precomputed_ecmult_gen.c:3:
warning: secp256k1-sys@0.10.0: /usr/include/x86_64-linux-gnu/bits/stdio2.h:111:1: error: expected identifier or ‘(’ before ‘{’ token
warning: secp256k1-sys@0.10.0:   111 | {
warning: secp256k1-sys@0.10.0:       | ^
warning: secp256k1-sys@0.10.0: GNU compiler is not supported for this target
warning: secp256k1-sys@0.10.0: GNU compiler is not supported for this target
warning: secp256k1-sys@0.10.0: GNU compiler is not supported for this target
warning: secp256k1-sys@0.10.0: GNU compiler is not supported for this target
warning: secp256k1-sys@0.10.0: GNU compiler is not supported for this target

error: failed to run custom build command for `secp256k1-sys v0.10.0`

Caused by:
  process didn't exit successfully: `/var/www/Kraken/target/release/build/secp256k1-sys-af278a91dc73c6d7/build-script-build` (exit status: 1)
  --- stdout
  OUT_DIR = Some(/var/www/Kraken/target/x86_64-pc-windows-msvc/release/build/secp256k1-sys-6b3c23eb15e9fc2b/out)
  TARGET = Some(x86_64-pc-windows-msvc)
  OPT_LEVEL = Some(3)
  HOST = Some(x86_64-unknown-linux-gnu)
  cargo:rerun-if-env-changed=VCINSTALLDIR
  VCINSTALLDIR = None
  cargo:rerun-if-env-changed=CC_x86_64-pc-windows-msvc
  CC_x86_64-pc-windows-msvc = None
  cargo:rerun-if-env-changed=CC_x86_64_pc_windows_msvc
  CC_x86_64_pc_windows_msvc = None
  cargo:rerun-if-env-changed=TARGET_CC
  TARGET_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CROSS_COMPILE
  CROSS_COMPILE = None
  RUSTC_LINKER = None
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  RUSTC_WRAPPER = None
  cargo:warning=GNU compiler is not supported for this target
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some(false)
  CARGO_CFG_TARGET_FEATURE = Some(cmpxchg16b,fxsr,sse,sse2,sse3)
  cargo:rerun-if-env-changed=CFLAGS_x86_64-pc-windows-msvc
  CFLAGS_x86_64-pc-windows-msvc = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_pc_windows_msvc
  CFLAGS_x86_64_pc_windows_msvc = None
  cargo:rerun-if-env-changed=TARGET_CFLAGS
  TARGET_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  OUT_DIR = Some(/var/www/Kraken/target/x86_64-pc-windows-msvc/release/build/secp256k1-sys-6b3c23eb15e9fc2b/out)
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some(cmpxchg16b,fxsr,sse,sse2,sse3)
  cargo:rerun-if-env-changed=CFLAGS_x86_64-pc-windows-msvc
  CFLAGS_x86_64-pc-windows-msvc = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_pc_windows_msvc
  CFLAGS_x86_64_pc_windows_msvc = None
  cargo:rerun-if-env-changed=TARGET_CFLAGS
  TARGET_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  OUT_DIR = Some(/var/www/Kraken/target/x86_64-pc-windows-msvc/release/build/secp256k1-sys-6b3c23eb15e9fc2b/out)
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some(cmpxchg16b,fxsr,sse,sse2,sse3)
  cargo:rerun-if-env-changed=CFLAGS_x86_64-pc-windows-msvc
  CFLAGS_x86_64-pc-windows-msvc = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_pc_windows_msvc
  CFLAGS_x86_64_pc_windows_msvc = None
  cargo:rerun-if-env-changed=TARGET_CFLAGS
  TARGET_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:warning=GNU compiler is not supported for this target
  cargo:warning=In file included from /usr/include/stdio.h:894,
  cargo:warning=                 from depend/secp256k1/src/util.h:14,
  cargo:warning=                 from depend/secp256k1/src/field.h:10,
  cargo:warning=                 from depend/secp256k1/src/group.h:10,
  cargo:warning=                 from depend/secp256k1/src/precomputed_ecmult_gen.c:3:
  cargo:warning=/usr/include/x86_64-linux-gnu/bits/stdio2.h:111:1: error: expected identifier or ‘(’ before ‘{’ token
  cargo:warning=  111 | {
  cargo:warning=      | ^
  cargo:warning=GNU compiler is not supported for this target
  cargo:warning=GNU compiler is not supported for this target
  cargo:warning=GNU compiler is not supported for this target
  cargo:warning=GNU compiler is not supported for this target
  cargo:rerun-if-env-changed=AR_x86_64-pc-windows-msvc
  AR_x86_64-pc-windows-msvc = None
  cargo:rerun-if-env-changed=AR_x86_64_pc_windows_msvc
  AR_x86_64_pc_windows_msvc = None
  cargo:rerun-if-env-changed=TARGET_AR
  TARGET_AR = None
  cargo:rerun-if-env-changed=AR
  AR = None
  cargo:warning=GNU compiler is not supported for this target
  cargo:rerun-if-env-changed=ARFLAGS_x86_64-pc-windows-msvc
  ARFLAGS_x86_64-pc-windows-msvc = None
  cargo:rerun-if-env-changed=ARFLAGS_x86_64_pc_windows_msvc
  ARFLAGS_x86_64_pc_windows_msvc = None
  cargo:rerun-if-env-changed=TARGET_ARFLAGS
  TARGET_ARFLAGS = None
  cargo:rerun-if-env-changed=ARFLAGS
  ARFLAGS = None

  --- stderr


  error occurred: Failed to find tool. Is `lib.exe` installed?
```

Am I missing something obivous?

### PR DESCRIPTION
**Pull request by apoelstra**
Fixes #734

### CODE REVIEW

**Review by apoelstra — COMMENTED** [review]
Successfully ran local tests on b66bae7d5b35781dc29f0c861f2ae22283ef2bce.

**Review by Kixunil — APPROVED** [review]
ACK b66bae7d5b35781dc29f0c861f2ae22283ef2bce

**Comment by Kixunil** [comment]
I wonder if upstream maintainers would be open to cleaning this up on their end so that we wouldn't need these potentially-fragile patches.

**Comment by apoelstra** [comment]
I think so -- they have the `USE_EXTERNAL_DEFAULT_CALLBACKS` config flag which disables most of the stdio-calling code, for example. And that was largely at our request.

In this case,  they added this code which isn't even used! (Its purpose is to make debugging/development easier.) I'm sure it was just an oversight that it could potentially break no-libc users.

**Comment by apoelstra** [comment]
Needs backport.

**Pull request merged**
