### PR TITLE
Move libsecp USE_ENDOMORPHISM option behind non-default feature flag

### PR DESCRIPTION
**Pull request by jonasnick**
The motivation behind this is to avoid risk of patent aggression.

### CODE REVIEW

**Comment by real-or-random** [comment]
Concept ACK, needs rebase

**Comment by elichai** [comment]
Could you explain the patent problems with the endomorphism feature? (just curious)

**Comment by real-or-random** [comment]
I think it's https://patents.google.com/patent/US7995752B2  (but no idea if there is more).

**Comment by jonasnick** [comment]
rebased

**Pull request merged**
