### PR TITLE
Add the prime of the secp256k1 field element.

### PR DESCRIPTION
**Pull request by rantan**
Hi, 

I want to get the prime of the secp256k1 field element on my project.
I thought it is proper that hosting in the constants.rs of this repo.
Could you merge this if you prefer?

### CODE REVIEW

**Comment by elichai** [comment]
Well we already have the group order, so I don't mind adding the field too.
But I'd use the name `field_size` or `field_order` instead.
May I ask why would you need that though?

(verified that it matches the prime field here: https://github.com/bitcoin-core/secp256k1/blob/96d8ccbd16090551aa003bfa4acd108b0496cb89/src/field_impl.h#L238)

**Comment by rantan** [comment]
Thank you for your reply.

I implemented Schnorr signature generation and verification on secp256k1 using this library [here](https://github.com/chaintope/rust-tapyrus/pull/8).
The field size was used in Jacobi symbol calculation.

> But I'd use the name field_size or field_order instead.
Which is better? I will update this PR.

**Comment by real-or-random** [comment]
I think `FIELD_SIZE` is good.

Please take note of https://github.com/bitcoin-core/secp256k1/pull/558.

**Comment by rantan** [comment]
I updated PR.

By the way, CI build is failing on master branch and also this PR. Does it avoid to merge this PR?
It looks building with cargo-web issue and I have no idea how can i fix it.

**Comment by rantan** [comment]
I found an issue about the failure and i understand the situation.
 https://github.com/rust-lang/rust/issues/68055

**Pull request merged**
