### PR TITLE
Fix ci

### PR DESCRIPTION
**Pull request by Kixunil**
Updated deprecated item and fixed cfg lints.

### CODE REVIEW

**Comment by apoelstra** [comment]
CI failure looks like https://github.com/rust-lang/cc-rs/issues/852 which we've fixed elsewhere by pinning `cc` to 1.0.79. I'm not sure why cc is not pinned in this part of CI.

**Comment by apoelstra** [comment]
Ah, when we compile the no_std_test using `cargo run --release --manifest-path=./no_std_test/Cargo.toml` cargo creates a new lockfile independent of our pinned one.

Maybe the simplest thing is to commit `no_std_test/Cargo.lock`. Alternately we can add a `cargo update -p cc --precise 1.0.79 --manifest-path=./no_std_test/Cargo.toml` line to `contrib/_test.sh` which might be less fragile.

**Comment by Kixunil** [comment]
They also suggest we use resolver v2. I believe that's a more principled approach and given we've bumped MSRV anyway we should use it.

**Comment by Kixunil** [comment]
It looks like that's not it (though updating edition doesn't hurt).

**Comment by Kixunil** [comment]
After trying to enable unwind I got his message:

> note: since the core library is usually precompiled with panic="unwind", rebuilding your crate with panic="abort" may not be enough to fix the problem

And indeed, it's referenced in core. I guess we need to recompile it.

**Comment by Kixunil** [comment]
Since downgrading isn't helping, I think the windows issue is caused by something using `HashMap`/`HashSet` causing it to link to `bcryptprimitives` to get RNG and the library is only available in wine 9.0+.

This can be solved by using a custom dockerfile which I'm not keen on doing.

**Comment by apoelstra** [comment]
Thanks for digging into this! I had my dates confused and thought that our MSRV was at the beginning of 2018, not the beginning of 2021. But apparently three extra years have happened..

**Comment by apoelstra** [comment]
I'll go ahead and ACK/merge this since it gets CI passing and is easy to whitelist on my end, but I see one more clippy nit:

```
error: doc list item missing indentation
   --> src/context.rs:252:13
    |
252 |         /// for `Secp256k1::gen_new()`).
    |             ^
    |
    = help: if this is supposed to be its own paragraph, add a blank line
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#doc_lazy_cont>
    = note: `-D clippy::doc-lazy-continuation` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(clippy::doc_lazy_continuation)]`
help: indent this line
    |
252 |         ///   for `Secp256k1::gen_new()`).
    |             ++
```

which we can address in another PR.

**Review by apoelstra — APPROVED** [review]
ACK 33a1893c14f242ba0653bbb26a9dad6f83ea81c2

**Pull request merged**
