### PR TITLE
Add `rand-alloc` feature

### PR DESCRIPTION
**Pull request by yukibtc**

### CODE REVIEW

**Comment by apoelstra** [comment]
I'm happy to add this feature, but right now much of this library is gated on `rand-std`. Should it instead be gated on `rand-alloc`?

**Comment by Kixunil** [comment]
I don't see the point if the feature is not used anywhere in our code.

**Comment by yukibtc** [comment]
I proposed this feature to avoid to add `rand` dependency with `alloc` and `getrandom` features in crates that already use secp256k1.
I know that I can just add it as dep, but it's to keep the code cleaned or to avoid to use different versions of `rand` between dependencies updates (by mistake).

Sorry, the next time I'll add a description.

**Comment by apoelstra** [comment]
This is a reasonable motivation but it adds another 2x split to our feature matrix. I'd be more confortable if there were a concrete benefit to this library (and I suspect there is one) -- e.g. if some `rand-std`-gated things could become `rand-alloc`-gated and therefore be more usable.

I also think that `rand-std` should imply `rand-alloc`, which reduces the feature matrix size.

As for `getrandom` I'm not sure about. It feels weird to stick it into some other feature like this.

**Comment by Kixunil** [comment]
Recently, I've seen a proposal to improve the situation by improving Cargo recently which would be the best solution. Doing this in every crate leads to blow up of features that need to be maintained.

Unfortunately this is a problem with many more crates. And yes, it did kick me in the ass at least once but reexporting features still doesn't look appealing.

**Pull request closed without merging**
