### PR TITLE
export `serde`, `rand` and `libc`; update version to 0.11.5

### LINKED ISSUE #79: Export rand
A crate that uses a different version of `rand` than this crate, say v0.5, can't use the "rand" features.
The error, `error[E0277]: the trait bound `rand::ThreadRng: rand::Rng` is not satisfied` seems to be caused by using different versions. 
One way around this is to export `rand` from `secp256k1` so that users can do e.g. `secp.generate_keypair(&mut secp256k1::rand::thread_rng())`

### PR DESCRIPTION
**Pull request by apoelstra**
Fixes #79

### CODE REVIEW

**Comment by stevenroose** [comment]
This is just all dependencies, right? I mean without an actual use case for serde and libc? It makes sense though. `pub extern crate` :)

fwiw, ACK

**Comment by apoelstra** [comment]
@stevenroose correct. It's generally good practice to use `pub extern crate` if you export any of another crate's types, for exactly cases like this. I didn't know about `pub extern crate` until a month ago so none of my projects use it yet.

**Comment by real-or-random** [comment]
Do you have a reference that this is good practice? Actually I don't think it's good practice because it means we break the API every time when we update our deps. The usual solution would be that we upgrade to a new `rand`. It seems that we can't to that because we promised to be compatible with Rust 1.14, and `rand` 0.5` requires Rust 1.22. But our README indicates that we did this promise for Debian users, and even the current Debian "old-stable" is already at Rust 1.24.

So if we cannot upgrade to `rand` 0.5, we should do this because fixes a real problem and is probably the most pragmatic solution. But if we can upgrade `rand`, I think we should do that instead.

**Comment by apoelstra** [comment]
@real-or-random debian stable is at 1.14 for i386 and arm64.

We already break our users by upgrading our deps because we expose types from these dependencies in our public API.

**Comment by real-or-random** [comment]
Oh yep, I'm not a Debian user, so I missed the different versions for different architectures.
And oh yep², if we wouldn't expose Rng, then #79 wasn't even an issue...

**Comment by apoelstra** [comment]
@dvdplm published 0.11.5.

**Pull request merged**
