### PR TITLE
Serde implementation for KeyPair type

### PR DESCRIPTION
**Pull request by dr-orlovsky**
Serde implementation for `KeyPair` type (which hadn't it before).

Based on #312 (includes all commits from that PR, will be rebased upon merge)

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
Why? Is Serde intended to be used for human-readable objects? Users would be totally reasonable to want to write secret key material to disk, and this makes them jump through hoops to do so. I'm all for removing foot guns, but not at the cost of disabling key library features without a flag.

**Comment by dr-orlovsky** [comment]
@TheBlueMatt am I getting you right that you propose to reverse feature flag introduced by this PR, so instead of `#[cfg(feature = "serde-secrets")]` we should do `#[cfg(not(feature = "serde-protect-secrets"))]`?

**Comment by elichai** [comment]
> @TheBlueMatt am I getting you right that you propose to reverse feature flag introduced by this PR, so instead of `#[cfg(feature = "serde-secrets")]` we should do `#[cfg(not(feature = "serde-protect-secrets"))]`?


I don't believe this should be guarded by a feature, it's one thing to protect against accidental logging secrets via Debug implementation, but it's another thing to prevent serialization.
IMHO Almost any user of `serde` in this library will probably also want to serialize secret keys and KeyPairs

**Comment by dr-orlovsky** [comment]
Well, I am a user of this library and _I do not want_ serde to default-serialize any private information. So I will prefer to be able to specify a feature which opts out from such thing.

**Comment by dr-orlovsky** [comment]
Removed from this PR everything related to preventing serde serialization. Now this PR is only about adding serde to KeyPair. It is still based on #312 since it requires display secret method.

**Comment by apoelstra** [comment]
Now that #312 is merged can this be a non-WIP?

**Comment by dr-orlovsky** [comment]
@apoelstra ready

**Review by apoelstra — DISMISSED** [review]
ACK 266ea949a7170004678bfc312558062ac46d3537

but now it needs a rebase :)

**Comment by dr-orlovsky** [comment]
@apoelstra rebased

**Review by apoelstra — APPROVED** [review]
ACK de77518d3a306b3755902e99a13eaaf38e738235

**Pull request merged**
