### PR TITLE
switch from travis to github workflows

### PR DESCRIPTION
**Pull request by apoelstra**

### CODE REVIEW

**Comment by apoelstra** [comment]
cc @elichai

**Comment by elichai** [comment]
Awesome!
is it possible to see how long it took all the tests to pass? (I wonder how much of it runs concurrently), 
also can you make a commit that makes something subtle in `contrib/tests.sh` fail so we can see the CI failing?

And in the future we can potentially add a cache for the `wasm` directory, so that `cargo install wasm-pack` will be fast. (this can be done in a future PR)

**Comment by real-or-random** [comment]
Just checking if https://github.com/bitcoin/bitcoin/issues/17803#issuecomment-570317499 is not a concern for us?

**Comment by apoelstra** [comment]
@elichai you can click "Actions" above and see the several failing early iterations of this PR

@real-or-random I think it's fine. If GH Actions were to modify our repository in some way we would absolutely notice and immediately shut it down. And unlike Core, there would not be a PR nightmare about how we knowingly gave Micro$oft write access to our repo and blah blah blah.

**Comment by real-or-random** [comment]
> @elichai you can click "Actions" above and see the several failing early iterations of this PR
> 
> @real-or-random I think it's fine. If GH Actions were to modify our repository in some way we would absolutely notice and immediately shut it down. And unlike Core, there would not be a PR nightmare about how we knowingly gave Micro$oft write access to our repo and blah blah blah.

Yes, and AFAIU most of the concerns about GitHub Actions turned out to be wrong, see my recent commend in the Core issue.

**Comment by apoelstra** [comment]
I agree with Marco's general distrust of Github. But for our case I think it's fine.

Also worthwhile to consider that almost everyone is just running the crates version of this repo, and I have the token for that, and obviously that will never be accessible to CI. So even if the CI were able to mess with the repo itself the damage would be limited.

**Review by elichai — APPROVED** [review]
:)

**Pull request merged**
