### PR TITLE
Adding schnorrsig::KeyPair::from_secret_key convenience function

### PR DESCRIPTION
**Pull request by dr-orlovsky**

### CODE REVIEW

**Review by apoelstra — APPROVED** [review]
ack bf9a276342d21ad1efba37d0d84307a52f6e085f

**Comment by Tibo-lg** [comment]
@dr-orlovsky is there a reason why the function doesn't borrow the secret key instead of taking ownership of it?

(also post merge nit, the `::key::` prefix seems unnecessary)

**Comment by dr-orlovsky** [comment]
SecretKey's are copyable objects and impls for copyable objects should take self ownership, not reference, according to the Rust API guidelines

**Comment by Tibo-lg** [comment]
@dr-orlovsky Thanks for answering. Do you have a reference to that guideline? I looked up a bit but the best I found is this clippy rule which doesn't indicate anything for `from` https://rust-lang.github.io/rust-clippy/master/#wrong_self_convention

The reason I find it a bit confusing personally is because the `from_secret_key` for `PublicKey` takes it as a reference so it feels a bit inconsistent.

**Comment by elichai** [comment]
IMHO @dr-orlovsky I generally right that Copy types should be passed by value, because that allows the compiler to make better optimizations usually (unless it's a non-inlinable function and the Copy type is bigger than say ~64 bytes).

But here because the C function cares just about a pointer to the type and the rest of the functions already pass by reference I think it would've been better to be a reference

**Pull request merged**
