### PR TITLE
Release tracking PR: `v0.29.0`

### PR DESCRIPTION
**Pull request by tcharding**
In preparation for release add a dummy changelog entry and bump the version.

### CODE REVIEW

**Comment by tcharding** [comment]
Looks to me like we can merge and release this even before the new `hashes` version is released, which is interesting.

**Comment by apoelstra** [comment]
While https://github.com/rust-bitcoin/rust-secp256k1/issues/673 is still open I think we should just get rid of the ranged dependency.

**Or** we could remove the `ThirtyTwoByteHash` trait in this release, but I don't think we want to do that.

**Review by apoelstra — APPROVED** [review]
ACK 5f9baaa7d5f6ff84dafb780a3ab90afcdb1dd5a9

**Comment by apoelstra** [comment]
Tagged and published.

**Pull request merged**
