### PR TITLE
Better lowmemory feature with precomputed ECMULT

### PR DESCRIPTION
**Pull request by devrandom**
Based on @justinmoon's no_std branch

Reduces the memory cost of a secp context from about 64KB to 704 bytes, while increasing the code section size by 62KB.

Also greatly reduces stack utilization while setting up the context.  Previously, about 200KB were being used during context generation, and now we can fit in less than 64KB RAM.

### CODE REVIEW

**Comment by RCasatta** [comment]
Nice improvement
How secp256k1-sys/depend/config/ecmult_static_context.h is built?
Ideally should be created with build.rs ?

**Comment by elichai** [comment]
ping @laanwj who originally added this feature

**Comment by elichai** [comment]
IMHO This sound interesting mostly because of the stack utilization during context creation (related https://github.com/bitcoin-core/secp256k1/issues/188) but I'm not an embedded person so hard for me to judge that use case.
(also semi related: https://github.com/bitcoin-core/secp256k1/issues/893)

**Comment by devrandom** [comment]
Unfortunately, `checked_malloc` has been patched out of `util.h` (why?), giving:

```
$ gcc -I. -I./src -Wall -Wextra -Wno-unused-function -g -O2 -c src/gen_context.c -o gen_context.o
$ gcc -Wall -Wextra -Wno-unused-function -g -O2  gen_context.o -o gen_context
/usr/bin/ld: gen_context.o: in function `main':
/home/dev/proj/rust-secp256k1/secp256k1-sys/depend/secp256k1/src/gen_context.c:59: undefined reference to `checked_malloc'
collect2: error: ld returned 1 exit status
```

I'll look into patching `gen_context.c` to match.

**Comment by devrandom** [comment]
Actually, this seems somewhat difficult, because:

- the cc crate doesn't produce binaries, only libraries
- when cross-compiling, the cc crate would be targeting the guest architecture, but we need `gen_context` for the host architecture

**Comment by devrandom** [comment]
How do you feel about doing the same thing for the regular memory case?  It would eliminate people worrying about the cost of creating and keeping contexts due to CPU/memory costs.  cc @TheBlueMatt 

Maybe separately feature gated, but enabled by default.

**Comment by real-or-random** [comment]
I understand the need for this but I don't think it's the right approach to tackle it here.

This should be solved upstream and we more or less agree that pregenerated files should be part of the solution, see the discussion here. https://github.com/bitcoin-core/secp256k1/pull/918#issuecomment-818673827 

Once this has been done, integrating this here in the rust bindings should be a matter of turning a flag on (if at all).

**Comment by real-or-random** [comment]
Now that https://github.com/bitcoin-core/secp256k1/pull/988 and https://github.com/bitcoin-core/secp256k1/pull/1042 have been merged, we should get this feature for free by just updating the secp256k1 tree.

**Pull request closed without merging**
