### PR TITLE
Add sign_ecdsa_with_noncedata and sign_ecdsa_recoverable_with_noncedata

### LINKED ISSUE #424: Add support for noncedata in secp.sign_ecdsa and secp.sign_ecdsa_recoverable
I would like to add (and am willing to make a PR) these two new methods.

I propose the names be `sign_ecdsa_with_noncedata` and `sign_ecdsa_recoverable_with_noncedata` and their function signatures add an extra argument at the end of type `[u8; 32]` and called `noncedata`.

Questions:

1. I would be willing to do this PR, but I want to get an idea of the willingness to add this to the API. Any objections?
2. Should I also add a new wrapper struct (similar to the other structs such as `Message` etc.)?

### PR DESCRIPTION
**Pull request by junderw**
Fixes #424

As discussed on [IRC](https://gnusha.org/bitcoin-rust/2022-03-19.log) (starts at 09:14).

These methods will allow for users to generate multiple signatures with the same private key and message by utilizing one of the `Variants` mention in RFC6979 which is exposed by libsecp256k1 via the `noncedata` argument.

The reasoning behind adding this is to allow our library to migrate from using the -sys crate. Currently we support using this noncedata argument, and would like to continue doing so while at the same time migrating away from -sys crate.

### CODE REVIEW

**Comment by junderw** [comment]
I have verified the fixed test vectors with node-secp256k1.

**Comment by tcharding** [comment]
FWIW, seems sane to me. I had some nits during review but your PR is perfectly in line with the rest of the module so I didn't bother with them :)

Thanks!

**Comment by junderw** [comment]
Fixes #424

**Comment by apoelstra** [comment]
Where was this discussed on IRC? You can generate multiple signatures with the same privkey and message with or without extra noncedata.

It's fine to add these methods but they are not needed for security.

**Comment by junderw** [comment]
> they are not needed for security.

Perhaps my wording was off.

In other words: "You can generate multiple signatures with the same private key and message while still using RFC6979 deterministic nonce generation for signatures."

This is not to say non-RFC6979-compliant schemes can not be secure, though.

**Comment by junderw** [comment]
IRC logs: https://gnusha.org/bitcoin-rust/2022-03-19.log

Starts at 09:14

**Comment by apoelstra** [comment]
From your logs, and this conversation, I am even more confused about the motivation for this. Low-R is directly supported by the library in the [sign_ecdsa_grind_r](https://docs.rs/secp256k1/latest/secp256k1/struct.Secp256k1.html#method.sign_ecdsa_grind_r) function.

This PR does nothing to change whether or not the user can switch off of RFC6979, it only gives them the option to pass extra entropy into 6979 (ok, this technically deviates from the spec, but it's still morally 6979).

>In other words: "You can generate multiple signatures with the same private key and message while still using RFC6979 deterministic nonce generation for signatures."

Yes. But this has nothing at all to do with the ability to add extra entropy.

**Comment by apoelstra** [comment]
Anyway concept ACK adding this functionality. Though I'd appreciate if you edited the PR description to say that it's because it's a libsecp functionality that you are using, and want to keep using, rather than the "security" justification.

**Comment by junderw** [comment]
> this technically deviates from the spec

While true that this functionality is only mentioned in the `3.6.  Variants` section under the 2nd bullet point (`"Additional data may be added to the input of HMAC, concatenated after bits2octets(H(m)):"`) it's one of those cases where "is part of the spec" is grey depending on what one considers "the spec"... since it's a semi-official "Variant" of the spec.

---

> I am even more confused about the motivation for this. Low-R is directly supported by the library in the sign_ecdsa_grind_r function.

I mention possibly using the low R function this library provides if we decided to explicitly remove the noncedata feature from our library.

> [From IRC]:
> 11:30 < junderw[m]> We could **move low R grinding to this lower API that uses Rust, and then use the low R grinding method rust-bitcoin has.**
> 11:30 < junderw[m]> But that's a breaking change, and a lot of shuffling around to **explicitly remove a feature that someone requested.**

We would need to remove the ability to add in the `"Variant RFC6979" aka noncedata` feature from our library, which was explicitly asked for by a user.

I only mentioned "low R" feature because it's the only time that any of our other higher level libraries make use of the noncedata feature, but I then admitted that our only use of the feature could theoretically be replaced by removing noncedata support and just wrapping the low R function from this library, but that would only be if we explicitly wanted to remove noncedata support, which we don't.

In retrospect, I shouldn't have mentioned anything unrelated to the motivation of this feature addition. Including the information of how our other libraries use the feature and how those use cases could be replaced by using another feature in this library is irrelevant to my case. The minimal info I should have relayed was:

1. Users asked for noncedata support, so we added it long before switching to Rust+WASM and are maintaining it
2. We are trying to move away from -sys crate we use currently
3. noncedata support was not in the main crate

---

> I'd appreciate if you edited the PR description to say that it's because it's a libsecp functionality that you are using, and want to keep using, rather than the "security" justification.

Done.

**Comment by apoelstra** [comment]
Thanks! Sorry for all the noise -- concept ACK this PR and its description. I will review it more carefully tomorrow.

**Review by apoelstra — APPROVED** [review]
ACK f93ca813481ae0d1bad0504319e0f942b62979e1

**Comment by apoelstra** [comment]
Looks good to me! I'm a little skeptical that the `_pointer` variants are super useful but they don't hurt anything.

**Comment by junderw** [comment]
:+1: I don't mind if they get refactored away someday.

I tend to split things into multiple lines and add descriptive extra variables to make the lines shorter and easier to read.

**Pull request merged**
