### PR TITLE
Impl Ord and PartialOrd for RecoverableSignature

### PR DESCRIPTION
**Pull request by benthecarman**

### CODE REVIEW

**Comment by apoelstra** [comment]
Do you need the ordering to be consistent between LE and BE machines? If so, you probably need to serialize them before comparing, `#derive` will do the wrong thing. (We probably should fix this in `ffi::RecoverableSignature` actually.)

**Comment by benthecarman** [comment]
> Do you need the ordering to be consistent between LE and BE machines? If so, you probably need to serialize them before comparing, `#derive` will do the wrong thing. (We probably should fix this in `ffi::RecoverableSignature` actually.)

Yeah that'd be ideal. How do I do that?

**Comment by apoelstra** [comment]
>Yeah that'd be ideal. How do I do that?

See for example what we did with the regular signatures: https://github.com/rust-bitcoin/rust-secp256k1/blob/master/secp256k1-sys/src/lib.rs#L278-L286

That's in secp256k1-sys, the FFI lib. Then in the main library you can just `#derive` it like you're doing now.

**Comment by benthecarman** [comment]
@apoelstra sorry never got to this, but looks like they already exist

https://github.com/rust-bitcoin/rust-secp256k1/blob/3373cc930eb67559d29eeb65effe0d64dd3e0152/secp256k1-sys/src/recovery.rs#L76

**Comment by Kixunil** [comment]
@benthecarman did you mean to close the PR?

**Comment by apoelstra** [comment]
@Kixunil no, it should be merged :). This PR is about deriving the ordering traits on the rust-secp repo. I had said that we couldn't derive these since it would pass thorugh to the rust-secp-sys ordering traits, which were implementation defined. But actually they aren't implementation-defined and there is no problem.

**Comment by Kixunil** [comment]
Oh, I thought this one does the same thing as the linked code but the linked is on `-sys` and this one is in non-`-sys`.

**Pull request merged**
