### PR TITLE
release 0.28.1

### PR DESCRIPTION
**Pull request by apoelstra**
We need a new rust-secp release to deal with the new rust-secp-sys release.

### CODE REVIEW

**Comment by apoelstra** [comment]
cc @Kixunil can you quickly ACK this?

**Comment by Kixunil** [comment]
This shouldn't be required for the sys crate since it's not semver-breaking. (And while we did strictly change the API it was broken in the first place so I believe non-semver-breaking version was correct.)

**Review by Kixunil — DISMISSED** [review]
ACK 940e56f1fb6bf826c5ac556c5d7e6d2a1f148844

**Comment by apoelstra** [comment]
@Kixunil the change in -sys was semver-breaking because we changed the signature of a publicly-exposed FFI function. rust-secp assumed that signature, and was therefore broken by it.

**Comment by apoelstra** [comment]
I do think this semver break is okay because it was a security-sensitive fix to an objectively wrong signature, which is why I'm updating rust-secp rather than reverting the change...but it is a semver break.

**Comment by apoelstra** [comment]
Oops, need re-ack. I forgot to update the lockfiles.

**Review by sanket1729 — APPROVED** [review]
utACK 0ed5a5582976bb0ba8f4abacb76e0d4cab41693b

**Comment by Kixunil** [comment]
> the change in -sys was semver-breaking

If it was then it should've been 0.10, not 0.9. :) But I claim it isn't since it was already broken. (Maybe subtly broken; this is in line with Rusts policy of fixing soundenss bugs which I believe is a great one.)

And since we didn't bump semver-majoor version this bump is not **required** but neither harmful. (And serialized signature is nice...)

**Review by Kixunil — APPROVED** [review]
ACK 0ed5a5582976bb0ba8f4abacb76e0d4cab41693b

**Comment by apoelstra** [comment]
> And since we didn't bump semver-majoor version this bump is not **required** but neither harmful. (And serialized signature is nice...)

It *is* required because we broke compilation of rust-secp :).

**Comment by Kixunil** [comment]
Oh, I see now, didn't realize the previous change updated stuff in non-sys crate too.

**Pull request merged**
