### PR TITLE
Update the `secp256k1-sys` codebase to version v0.6.

### PR DESCRIPTION
**Pull request by jlest01**
This PR updates the `secp256k1-sys` codebase to version v0.6.
I'm not sure if there are more steps involved, but these commits work fine in https://github.com/rust-bitcoin/rust-secp256k1/pull/716.

### CODE REVIEW

**Comment by jlest01** [comment]
@apoelstra thanks. I added two new initial commits.

**Comment by apoelstra** [comment]
Can you also update the Cargo-recent.lock and Cargo-minimal.lock files in the repo?

**Comment by jlest01** [comment]
@apoelstra done. Thanks

**Comment by jlest01** [comment]
I had squashed everything, but then I realized you to do it after the review.
`Cargo-recent.lock` and `Cargo-minimal.lock` were changed in https://github.com/rust-bitcoin/rust-secp256k1/pull/764/commits/d88e6c27096b97a543e397e2649325bcf0bf04cb

**Comment by apoelstra** [comment]
utACK 0cdc758a56360bf58a851fe91085a327ec97685a

Thanks for iterating!!

If you squash everything I can do a tested ACK and merge it. (I already tested the tip so it will pass after squashing.)

**Comment by apoelstra** [comment]
Err, utack 32a533c130c855dfb7e7d4a6df910e530db8b4e2 I mean. Copied the wrong commit.

**Comment by jlest01** [comment]
Thanks for reviewing. All commits squashed.

**Review by apoelstra — APPROVED** [review]
ACK 06ab8d0c1eb1c450f5e3f49aff3b2de6ce7eaa39; successfully ran local tests; thanks for iterating!

**Pull request merged**
