### PR TITLE
Add a feature to disable replacing C symbols with rust

### PR DESCRIPTION
**Pull request by elichai**
Hi,
Requested in IRC by @TheBlueMatt the main use case is bitcoin core integration.
such that you can use upstream's libsecp256k1 with this library.

this feature *is not* compatible with `no-std`.

### CODE REVIEW

**Comment by apoelstra** [comment]
Can you put a `// Do not use this feature!` or something warning that this is a bad/unsupported thing and we are only doing it for Core's sake, because Core shares developers with both this project and upstream libsecp?

**Comment by elichai** [comment]
Done. took the liberty and added that warning to `fuzztarget` too.
(FYI #154 )

**Comment by TheBlueMatt** [comment]
ACK. This  176 appears to fully solve my issues linking into Core with its libsecp.

**Comment by apoelstra** [comment]
I like the comment. Matt's ACK is good enough for me.

**Comment by stevenroose** [comment]
@elichai @TheBlueMatt so are you saying that you are using the C symbols exported by rust-secp? I don't think that's what this crate is supposed for, is it?

Doing that would also stop working with https://github.com/rust-bitcoin/rust-secp256k1/pull/169, which arguably makes this crate more interoperable with other systems.

**Comment by stevenroose** [comment]
Oh I think I understood it wrong. You're using this library with the libsecp symbols already exported in Core?

That already makes more sense to me, but I think that will still be hard to make work with https://github.com/rust-bitcoin/rust-secp256k1/pull/169.

**Comment by TheBlueMatt** [comment]
Right, for #169 we’ll need a feature to skip the -sys dependency and not use version-tagged symbols.

**Pull request merged**
