### PR TITLE
Bump secp256k1-sys to v0.9.0

### PR DESCRIPTION
**Pull request by tcharding**
We just bumped the version of `secp256k1`, since we recently added a new public function to `secp256k1-sys` we need to bump the minor version number there too.

Should have been done as part of #588, its hard to get good help :)

### CODE REVIEW

**Comment by apoelstra** [comment]
Please bump the patch version. Bumping the minor version is interpreted by Cargo as a breaking change.

**Comment by tcharding** [comment]
Oh because its pre-1.0? Post 1.0.0 an API addition requires bump of minor version, right?

**Comment by tcharding** [comment]
Oh bother, we have to fix symbol names too.

**Comment by Kixunil** [comment]
> Oh because its pre-1.0?

Yes.

**Comment by tcharding** [comment]
>  Bumping the minor version is interpreted by Cargo as a breaking change.

FTR I'm not convinced bumping the patch version is correct here but I'm deferring to @apoelstra and @Kixunil on it. Will convince myself at a later time and date.

**Comment by tcharding** [comment]
Force pushed to remove changes to `depend/secp256k1/CHANGELOG.md`

**Review by apoelstra — APPROVED** [review]
ACK 5ae136d7bd84407812d330accb8da2e824999deb

**Comment by apoelstra** [comment]
Tagged and published secp256k1-sys 0.8.1 and secp256k1 0.27.0

**Pull request merged**
