### PR TITLE
secp-sys: Use NonNull in API instead of *mut T

### LINKED ISSUE #546: Clean up `NonNull` usage
Moving discussion from https://github.com/rust-bitcoin/rust-secp256k1/commit/082c3bdd1c5a3f661ce806445f0a7a5e8ce92277#r91588011

In #542 we introduced the `NonNull` field for our internal secp context pointer. As @Kixunil observed, we could actually clean up this code by replacing `NonNull::new_unchecked` with `NonNull::new().unwrap_or_else(|| /* our existing allocation failure-checking code */)`. But when trying to implement this I got a bit frustrated because it would require that we fish `NonNull<T>`s through the FFI, which currently expects and returns `*mut T`s.

According to [this SE post](https://stackoverflow.com/questions/49392712/is-it-valid-to-use-ptrnonnull-in-ffi) we can use `NonNull<T>` in FFI bindings that are expecting `*mut T`. (The reasoning is that `NonNull` is marked `#[refr(transparent)]`...and it's hard for me to think why they'd have this marker, other than to enable FFI bindings like this.)

This would be semver-breaking but I believe it would more accurately document the FFI API, if we were to replace all `*mut Context` pointers with `NonNull<Context>`. The C code currently does `VERIFY_CHECK(ctx != NULL)` for context objects and then assumes that its passed pointers are non-NULL. With our current compilation flags, `VERIFY_CHECK` is compiled to nothing at all, so basically right now if you pass NULL context pointers to our FFI you'll get UB.

One unfortunate thing is that this means that we wouldn't be able to implement `CPtr` for `secp256k1::Context`, which is our designated "expose types from `secp256k1-sys` which is not stable" semver escape hatch.

cc @Kixunil

### PR DESCRIPTION
**Pull request by tcharding**
Currently we expect non-null pointers when we take `*mut T` parameters, however we do not check that the pointers are non-null because we never set VERIFY in our C build. We can use the `NonNull` type to enforce no-null-ness as long as we use `NonNull::new`. In a couple of instances we manually check that a buffer is not empty and therefore that the pointer to it is non-null so we can safely use `NonNull::new_unchecked`.

Replace mutable pointer parameters `*mut T` (e.g. `*mut c_void`) and return types with `NonNull<T>`.

Fix #546

### Note

The description above fully explains the issue to the best of my knowledge, if the description is not spot on then I'm not fully understanding the issue. Please correct me if this is the case.

> One unfortunate thing is that this means that we wouldn't be able to implement CPtr for secp256k1::Context, which is our designated "expose types from secp256k1-sys which is not stable" semver escape hatch.

You've lost me here? `secp256k1::Context` is a trait did you mean `secp256k1::Secp256k1` or `secp256k1_sys::Context`?

### CODE REVIEW

**Comment by apoelstra** [comment]
Thanks! We could actually go a bit further and `NonNull`-ize the context pointers in **all** the FFI functions, even signing and verification etc. Then we wouldn't even need to use `ptr.as_ptr()` everywhere. (Though at the cost of losing the distinction between `*mut` and `*const` ... which sucks.)

>You've lost me here? secp256k1::Context is a trait did you mean secp256k1::Secp256k1 or secp256k1_sys::Context?

I mean `secp256k1::CPtr`.

**Comment by sanket1729** [comment]
Are we sure we want this? My understanding is that FFI sys deliberately should not do anything clever and _just_ translate the C interface. The wrappers can do the clever stuff. 

For linker reasons, there should only ever by one sys crate in project build dependency. Anyone building their own high-level wrappers around the sys crate is not bound by our choice. The general design rationale here is not to do not anything and deal with raw pointers. 
See open-ssl sys: https://github.com/sfackler/rust-openssl/blob/master/openssl-sys/src/handwritten/aes.rs
Even the bindgen autogenerated bindgens follow this principle.

**Comment by apoelstra** [comment]
>Are we sure we want this? My understanding is that FFI sys deliberately should not do anything clever and just translate the C interface. The wrappers can do the clever stuff.

The C interface is "takes a non-null pointer at penalty of UB". Arguably using `NonNull` rather than `*mut T` is more correct.

>Even the bindgen autogenerated bindgens follow this principle.

That's because bindgen does not (and cannot) understand the contracts required by C code.

**Comment by Kixunil** [comment]
`*const` does suck indeed and I'm not sure if we should translate `const` pointers like that. AFAIK the semantics of `NonNull` is similar to that of a `Box`.

**Comment by apoelstra** [comment]
Ok, I'm happy to take this PR as-is then. Is that what you're suggesting @Kixunil ?

**Comment by Kixunil** [comment]
Went to double-check and after reading https://internals.rust-lang.org/t/seperating-nonnull-into-nonnullmut-and-nonnullconst/11083 and https://internals.rust-lang.org/t/what-is-the-real-difference-between-const-t-and-mut-t-raw-pointers/6127

I came to the conclusion that neither `NonNull<T>` nor `*const T` are great. I wouldn't be against our own `#[repr(transparent)] pub struct NonNullConst(NonNull<T>);` type but maybe it's too much.

**Comment by apoelstra** [comment]
@Kixunil nice, thanks for the links -- but this PR only replaces `*mut T`s with `NonNull`s and doesn't touch the `*const` cases, which I think is ok?

**Comment by Kixunil** [comment]
Yes, I think it's OK.

**Review by apoelstra — APPROVED** [review]
ACK 9b07e8e8c59938b6b681368917138d1c3938d20b

**Pull request merged**
