### PR TITLE
Re-support WASM via simple stub headers

### LINKED ISSUE #134: Building for wasm on macOS 10.14
I was able to build `rust-secp256k1` in a Ubuntu vagrant box, however am still running into issues on macOS 10.14.

The error originates from `depend/secp256k1/contrib/lax_der_parsing.c:7` and is caused by `/usr/include/machine/_types.h:34:2: error: architecture not supported`.

Clang version:
```sh
$ clang --version
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
I have tried separately installing and compiling with Clang 8 via Homebrew, and receive the same compilation issue.

Below is the full output:
```sh
$ wasm-pack build
[INFO]: 🎯  Checking for the Wasm target...
[INFO]: 🌀  Compiling to Wasm...
   Compiling secp256k1 v0.14.1
error: failed to run custom build command for `secp256k1 v0.14.1`

Caused by:
  process didn't exit successfully: `/wasm-demo/target/release/build/secp256k1-babdfc45bf44ba99/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("wasm32-unknown-unknown")
OPT_LEVEL = Some("3")
HOST = Some("x86_64-apple-darwin")
CC_wasm32-unknown-unknown = None
CC_wasm32_unknown_unknown = None
TARGET_CC = None
CC = None
CFLAGS_wasm32-unknown-unknown = None
CFLAGS_wasm32_unknown_unknown = None
TARGET_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
CC_wasm32-unknown-unknown = None
CC_wasm32_unknown_unknown = None
TARGET_CC = None
CC = None
CFLAGS_wasm32-unknown-unknown = None
CFLAGS_wasm32_unknown_unknown = None
TARGET_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
running: "clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "--target=wasm32-unknown-unknown" "-I" "depend/secp256k1/" "-I" "depend/secp256k1/include" "-I" "depend/secp256k1/src" "-Wall" "-Wextra" "-DSECP256K1_BUILD=1" "-DUSE_NUM_NONE=1" "-DUSE_FIELD_INV_BUILTIN=1" "-DUSE_SCALAR_INV_BUILTIN=1" "-DENABLE_MODULE_ECDH=1" "-DUSE_EXTERNAL_DEFAULT_CALLBACKS=1" "-DECMULT_WINDOW_SIZE=15" "-DUSE_FIELD_10X26=1" "-DUSE_SCALAR_8X32=1" "-o" "/wasm-demo/target/wasm32-unknown-unknown/release/build/secp256k1-c0bc0977ed6381c0/out/depend/secp256k1/contrib/lax_der_parsing.o" "-c" "depend/secp256k1/contrib/lax_der_parsing.c"
cargo:warning=In file included from depend/secp256k1/contrib/lax_der_parsing.c:7:
cargo:warning=In file included from /usr/include/string.h:61:
cargo:warning=In file included from /usr/include/_types.h:27:
cargo:warning=In file included from /usr/include/sys/_types.h:32:
cargo:warning=/usr/include/sys/cdefs.h:784:2: error: Unsupported architecture
cargo:warning=#error Unsupported architecture
cargo:warning= ^
cargo:warning=In file included from depend/secp256k1/contrib/lax_der_parsing.c:7:
cargo:warning=In file included from /usr/include/string.h:61:
cargo:warning=In file included from /usr/include/_types.h:27:
cargo:warning=In file included from /usr/include/sys/_types.h:33:
cargo:warning=/usr/include/machine/_types.h:34:2: error: architecture not supported
cargo:warning=#error architecture not supported
cargo:warning= ^
cargo:warning=In file included from depend/secp256k1/contrib/lax_der_parsing.c:7:
cargo:warning=In file included from /usr/include/string.h:61:
cargo:warning=In file included from /usr/include/_types.h:27:
cargo:warning=/usr/include/sys/_types.h:55:9: error: unknown type name '__int64_t'; did you mean '__int128_t'?
cargo:warning=typedef __int64_t       __darwin_blkcnt_t;      /* total blocks */
cargo:warning=        ^
cargo:warning=note: '__int128_t' declared here
cargo:warning=/usr/include/sys/_types.h:56:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
cargo:warning=typedef __int32_t       __darwin_blksize_t;     /* preferred block size */
cargo:warning=        ^
cargo:warning=note: '__int128_t' declared here
cargo:warning=/usr/include/sys/_types.h:57:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
cargo:warning=typedef __int32_t       __darwin_dev_t;         /* dev_t */
cargo:warning=        ^
cargo:warning=note: '__int128_t' declared here
cargo:warning=/usr/include/sys/_types.h:60:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
cargo:warning=typedef __uint32_t      __darwin_gid_t;         /* [???] process and group IDs */
cargo:warning=        ^
cargo:warning=note: '__uint128_t' declared here
cargo:warning=/usr/include/sys/_types.h:61:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
cargo:warning=typedef __uint32_t      __darwin_id_t;          /* [XSI] pid_t, uid_t, or gid_t*/
cargo:warning=        ^
cargo:warning=note: '__uint128_t' declared here
cargo:warning=/usr/include/sys/_types.h:62:9: error: unknown type name '__uint64_t'; did you mean '__uint128_t'?
cargo:warning=typedef __uint64_t      __darwin_ino64_t;       /* [???] Used for 64 bit inodes */
cargo:warning=        ^
cargo:warning=note: '__uint128_t' declared here
cargo:warning=/usr/include/sys/_types.h:68:9: error: unknown type name '__darwin_natural_t'
cargo:warning=typedef __darwin_natural_t __darwin_mach_port_name_t; /* Used by mach */
cargo:warning=        ^
cargo:warning=/usr/include/sys/_types.h:70:9: error: unknown type name '__uint16_t'; did you mean '__uint128_t'?
cargo:warning=typedef __uint16_t      __darwin_mode_t;        /* [???] Some file attributes */
cargo:warning=        ^
cargo:warning=note: '__uint128_t' declared here
cargo:warning=/usr/include/sys/_types.h:71:9: error: unknown type name '__int64_t'; did you mean '__int128_t'?
cargo:warning=typedef __int64_t       __darwin_off_t;         /* [???] Used for file sizes */
cargo:warning=        ^
cargo:warning=note: '__int128_t' declared here
cargo:warning=/usr/include/sys/_types.h:72:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
cargo:warning=typedef __int32_t       __darwin_pid_t;         /* [???] process and group IDs */
cargo:warning=        ^
cargo:warning=note: '__int128_t' declared here
cargo:warning=/usr/include/sys/_types.h:73:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
cargo:warning=typedef __uint32_t      __darwin_sigset_t;      /* [???] signal set */
cargo:warning=        ^
cargo:warning=note: '__uint128_t' declared here
cargo:warning=/usr/include/sys/_types.h:74:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
cargo:warning=typedef __int32_t       __darwin_suseconds_t;   /* [???] microseconds */
cargo:warning=        ^
cargo:warning=note: '__int128_t' declared here
cargo:warning=/usr/include/sys/_types.h:75:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
cargo:warning=typedef __uint32_t      __darwin_uid_t;         /* [???] user IDs */
cargo:warning=        ^
cargo:warning=note: '__uint128_t' declared here
cargo:warning=/usr/include/sys/_types.h:76:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
cargo:warning=typedef __uint32_t      __darwin_useconds_t;    /* [???] microseconds */
cargo:warning=        ^
cargo:warning=note: '__uint128_t' declared here
cargo:warning=In file included from depend/secp256k1/contrib/lax_der_parsing.c:7:
cargo:warning=In file included from /usr/include/string.h:64:
cargo:warning=/usr/include/sys/_types/_size_t.h:31:9: error: unknown type name '__darwin_size_t'
cargo:warning=typedef __darwin_size_t        size_t;
cargo:warning=        ^
cargo:warning=In file included from depend/secp256k1/contrib/lax_der_parsing.c:7:
cargo:warning=In file included from /usr/include/string.h:141:
cargo:warning=In file included from /usr/include/sys/_types/_rsize_t.h:30:
cargo:warning=/usr/include/machine/types.h:37:2: error: architecture not supported
cargo:warning=#error architecture not supported
cargo:warning= ^
cargo:warning=In file included from depend/secp256k1/contrib/lax_der_parsing.c:7:
cargo:warning=In file included from /usr/include/string.h:141:
cargo:warning=/usr/include/sys/_types/_rsize_t.h:31:9: error: unknown type name '__darwin_size_t'
cargo:warning=typedef __darwin_size_t        rsize_t;
cargo:warning=        ^
cargo:warning=fatal error: too many errors emitted, stopping now [-ferror-limit=]
cargo:warning=20 errors generated.
exit code: 1

--- stderr
thread 'main' panicked at '

Internal error occurred: Command "clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "--target=wasm32-unknown-unknown" "-I" "depend/secp256k1/" "-I" "depend/secp256k1/include" "-I" "depend/secp256k1/src" "-Wall" "-Wextra" "-DSECP256K1_BUILD=1" "-DUSE_NUM_NONE=1" "-DUSE_FIELD_INV_BUILTIN=1" "-DUSE_SCALAR_INV_BUILTIN=1" "-DENABLE_MODULE_ECDH=1" "-DUSE_EXTERNAL_DEFAULT_CALLBACKS=1" "-DECMULT_WINDOW_SIZE=15" "-DUSE_FIELD_10X26=1" "-DUSE_SCALAR_8X32=1" "-o" "/wasm-demo/target/wasm32-unknown-unknown/release/build/secp256k1-c0bc0977ed6381c0/out/depend/secp256k1/contrib/lax_der_parsing.o" "-c" "depend/secp256k1/contrib/lax_der_parsing.c" with args "clang" did not execute successfully (status code exit code: 1).

'

warning: build failed, waiting for other jobs to finish...
error: build failed
Error: Compiling your crate to WebAssembly failed
```

### PR DESCRIPTION
**Pull request by TheBlueMatt**
libsecp256k1 really only barely uses libc at all, and in practice,
things like memcpy/memcmp get optimized into something other than a
libc call. Thus, if we provide simple stub headers, things seem to
work with wasm-pack just fine.

Closes #134 I think.

### CODE REVIEW

**Comment by elichai** [comment]
It seems to be warning about missing `memcmp` https://travis-ci.org/github/rust-bitcoin/rust-secp256k1/jobs/675911448#L1813
But we currently don't use the scratch API so apparently removes it in linking and doesn't fail. 

I think I'm fine with merging this, I'm somewhat worried that the ABI might be incompatible between rust and C for this target (See https://github.com/rustwasm/team/issues/291#issuecomment-596625803) but if it works and users need it then I guess it's fine.

**Comment by TheBlueMatt** [comment]
> It seems to be warning about missing `memcmp` https://travis-ci.org/github/rust-bitcoin/rust-secp256k1/jobs/675911448#L1813
> But we currently don't use the scratch API so apparently removes it in linking and doesn't fail.

I think you're confused there - its complaining that we're implicitly *defining* it, whether it links is independent from whether it is defined implicitly or explicitly (and is based on declaration not definition). It may be that we aren't ever calling it, or, more likely, that its getting optimized into native memcmp, which seems more likely to me.

> I think I'm fine with merging this, I'm somewhat worried that the ABI might be incompatible between rust and C for this target (See [rustwasm/team#291 (comment)](https://github.com/rustwasm/team/issues/291#issuecomment-596625803)) but if it works and users need it then I guess it's fine.

Hmm, I'm a little confused by that comment - which ABI is he even referring to? Is it the stdlibc ABI, or is it also using different pointer/int sizes? The first doesn't hugely scare me here since we shouldn't be calling much of stdlibc, the second, obviously, would.

**Comment by elichai** [comment]
> I think you're confused there - its complaining that we're implicitly _defining_ it, whether it links is independent from whether it is defined implicitly or explicitly (and is based on declaration not definition)

You're right. My mistake.

> Hmm, I'm a little confused by that comment - which ABI is he even referring to? Is it the stdlibc ABI, or is it also using different pointer/int sizes? The first doesn't hugely scare me here since we shouldn't be calling much of stdlibc, the second, obviously, would.

I'm honestly not sure. if I knew for sure that the definitions of fundamental types was different between rust and C for this target I would've been against it, but I'm not. Which is why I said I'm a bit worried, because I didn't quite understood what they meant, and it's hard to find people who actually really know their stuff. Maybe I'll try Twitter

**Comment by TheBlueMatt** [comment]
Hmm, it seems like it would be super, duper strange for clang-LLVM to have different int sizes from rust-LLVM for the same target, no?

**Pull request merged**
