### PR TITLE
Using serde/alloc and serde/std with corresponding features

### PR DESCRIPTION
**Pull request by dr-orlovsky**

### CODE REVIEW

**Review by real-or-random — COMMENTED** [review]
Concept ACK

**Review by elichai — APPROVED** [review]
LGTM

**Comment by dr-orlovsky** [comment]
It will be nice to get it merged to complete no_std support. How many ACKs do we need for this? @TheBlueMatt

**Comment by devrandom** [comment]
are we missing some CI tests to catch these things?

**Comment by dr-orlovsky** [comment]
@devrandom we need cross-lib integration CI (impossible with GitHub) for that I assume

**Comment by devrandom** [comment]
> @devrandom we need cross-lib integration CI (impossible with GitHub) for that I assume

Actually, I'm confused now.  If this works in practice (not test failures, no failures in rust-bitcoin that depends on it), then it probably means that we don't actually use anything from `serde` that is gated by `std` or `alloc`.  If that's the case, then isn't it up to whatever crate that depends on this one to pull in features from `serde` that it needs, if it needs them?

**Comment by elichai** [comment]
Let me take back my ACK, it seems to me that this library never needs serde for the alloc/std stuff, so I don't see a reason why we should enable those features.
if downstream crates use serde by themselves they should import it and enable the features they need.

(that's also part of the reason why no tests "failed" here)

**Comment by apoelstra** [comment]
Closing as the value proposition is unclear and this seems stale.

**Pull request closed without merging**
