### PR TITLE
Add serde impl for KeyPair

### PR DESCRIPTION
**Pull request by elsirion**
The impl is added as a module instead of being a direct implementation since it uses the global context and users should be aware that.

### CODE REVIEW

**Review by apoelstra — APPROVED** [review]
ACK 1877e4db331862ab1b2d6ea9ee1431aaa926b715

It's a little unfortunate that serde depends on the global context, and also that deserialization is so very slow (involving a const-time EC mult), but I think this is alright. Or at least, hard to do better.

Would like at least one more ACK before mergign.

**Review by elichai — APPROVED** [review]
ACK 1877e4db331862ab1b2d6ea9ee1431aaa926b715
we can remove that feature gate next time we bump upstream, so even the precomp has signing context in it AFAIU

**Comment by apoelstra** [comment]
SGTM -- though bear in mind that it's not guaranteed for upstream to get rid of the context object for signing (or even make it "free") because of randomization. Though it may be cheap enough, next to the ec-mult, that we can just generate one inside the serde code..

**Comment by real-or-random** [comment]
> we can remove that feature gate next time we bump upstream, so even the precomp has signing context in it AFAIU

The `no_precomp` context is not a signing context on upstream master. In fact, `no_precomp` (plus its clones) is the only remaining way to obtain a non-signing context.

**Pull request merged**
