### PR TITLE
add c_int return type to EcdhHashFn signature, pub for types mod

### PR DESCRIPTION
**Pull request by shmishleniy**
#160

### CODE REVIEW

**Comment by elichai** [comment]
Fixing the declaration is good, but i'm unsure about exposing the types.
If you're using ffi's directly than you probably need to have access to the type primitives anyway somehow (libc/std::raw/your own) we only provide types needed for this library, it isn't supposed to be a general libc like.

But i'm unsure because we do expose the ffi so idk. @apoelstra what do you think?

**Comment by jonasnick** [comment]
Fwiw in rust-secp256k1-zkp we're doing using ffi via `use secp256k1::ffi::{Context, NonceFn, PublicKey};` but have our own copy of types.rs which we could remove (and don't have to keep up to date) if it was exported here.

**Comment by elichai** [comment]
@jonasnick does it provide anything that secp256k1-zkp requires? or will you have to add more types anyway?

**Comment by jonasnick** [comment]
It's the same c_types https://github.com/ElementsProject/rust-secp256k1-zkp/blob/master/secp256k1-zkp-sys/src/types.rs

**Comment by shmishleniy** [comment]
I need this fix to create SharedSecret with custom hash function instead of ffi::secp256k1_ecdh_hash_function_default.

I can create PR in case you are consider to add such functionality.
Here is implementation for master https://github.com/shmishleniy/rust-secp256k1/commit/e497a8482fa564008e17def53013502ec5e4b073

**Comment by apoelstra** [comment]
Should we take this opportunity to split out the ffi stuff into a `secp256k1-sys` crate?

**Comment by apoelstra** [comment]
Closing in light of #169 and #180. Please let me know if I'm mistaken and this is still needed.

**Pull request closed without merging**
