### PR TITLE
remove `Secp256k1::without_caps` from public API and all no-capability context args

### PR DESCRIPTION
**Pull request by apoelstra**

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
Can you tag the upstream PR that makes this not do a bunch of alloc? Currently it kinda sucks, but the API change overall is nice. Are we in a rush or can we wait until upstream fixes this.

**Comment by apoelstra** [comment]
No rush. This will force a new 0.11 version and it's not so bad that I'm itching to change it.

Upstream PR is https://github.com/bitcoin-core/secp256k1/pull/553

I will probably update it to also allow creating normal contexts using preallocated memory, so that will delay review.

**Comment by apoelstra** [comment]
In fact I definitely *don't* want to rush this because #44 #46 #52 should all go in 0.10.1 before any more breaking changes.

**Comment by apoelstra** [comment]
Closing in favor of #78

**Pull request closed without merging**
