### PR TITLE
Update vendored libsecp to 0.4.0

### PR DESCRIPTION
**Pull request by tcharding**
This replaces #645 and includes patches from that PR as well as two additional patches to update to v0.4.0

FTR I always forget how to do this and just hack my way around, what I did was:

1. Check out libsecp tag v0.4.0
2. Work out why the patch wasn't applying  (one function no longer exists)
3. Manually create a patch file using diff and copies of the original and modified util.h
4. cp the patch file to this repo, commit it and run the verdor script using the commit hash of the tagged commit

Question please: is there a way to do (3) using git?

### CODE REVIEW

**Comment by tcharding** [comment]
@apoelstra want to put me out of my misery please and tell me whats going on here?

**Comment by apoelstra** [comment]
Nothing off the top of my head, sorry.

**Comment by tcharding** [comment]
No sweat, thanks for checking.

**Comment by tcharding** [comment]
Gee wiz, @Davidson-Souza already di this in #627, very unobservant of me.

**Pull request closed without merging**
