### PR TITLE
feat: add sign_schnorr_no_aux_rand for Keypair

### PR DESCRIPTION
**Pull request by witter-deland**
#761 
https://github.com/kaspanet/rusty-kaspa/issues/586

### CODE REVIEW

**Comment by apoelstra** [comment]
In be017c27464daf14b174e67f23f504bdb3ad4b5f:

There is trailing whitespace on multiple lines.

But concept ACK.

**Comment by witter-deland** [comment]
fixed :)
> In [be017c2](https://github.com/rust-bitcoin/rust-secp256k1/commit/be017c27464daf14b174e67f23f504bdb3ad4b5f):
> 
> There is trailing whitespace on multiple lines.
> 
> But concept ACK.

**Comment by apoelstra** [comment]
In 9f75b633e48fddfe0b7165971042e5e8a7d6e5ba:

There is still a trailing space on line 1017 :)

**Comment by witter-deland** [comment]
fixed :)
> In [9f75b63](https://github.com/rust-bitcoin/rust-secp256k1/commit/9f75b633e48fddfe0b7165971042e5e8a7d6e5ba):
> 
> There is still a trailing space on line 1017 :)

**Comment by apoelstra** [comment]
Please squash these commits.

**Comment by witter-deland** [comment]
Done, thank you for your patience
> Please squash these commits.

**Review by apoelstra — APPROVED** [review]
ACK 2d29116fc9d53d7201a4fe4223eded9501bf3fa9; successfully ran local tests; thanks for iterating!

**Pull request merged**
