### PR TITLE
Disable some useless lints

### PR DESCRIPTION
**Pull request by TheBlueMatt**

### CODE REVIEW

**Comment by elichai** [comment]
Well we don't use any trait objects (and I would prefer to keep it like that).
But I can confirm that after this there are no warnings with default features.
ACK f09ff2a9de86f0a55a138fc2019e4d1dc68c11ab

**Comment by TheBlueMatt** [comment]
Oops, yea, I had just copied what I needed for all our other crates, of course now I actually cant build rust-secp with default features cause various things in rand appear to have broken, which is fun.

**Comment by elichai** [comment]
Really? for me it builds fine. even if I delete `Cargo.lock` and `./target` (also the CI passed)

**Comment by TheBlueMatt** [comment]
Heh, a coupe years may be quick given the current Rust ecosystem :(. By that point we may have lifetimes in C++ and we'll just switch back to that :joy:

**Pull request merged**
