### PR TITLE
Deprecate `Message::from_digest_slice`

### LINKED ISSUE #710: Deprecate `Message::from_digest_slice`?
There is `from_digest` method which is more straightforward for probably all use cases - any serious hash engine will output an array, not a slice/vec/whatever. And in the rare scenarios where people use hash engines with crappy API they can just call `.try_into().unwrap()` themselves - no need to pollute our API.

### PR DESCRIPTION
**Pull request by Kixunil**
Closes #710 

On top of #709

### CODE REVIEW

**Comment by tcharding** [comment]
Can be rebased now, #709 is in.

**Comment by apoelstra** [comment]
The hex-lit thing requires you update the lockfiles.

I'm not sure why CI isn't failing.

**Comment by Kixunil** [comment]
Done.

**Review by apoelstra — APPROVED** [review]
ACK 939bf9ed5ea87b109376f6c8de6466ff014ce737

**Pull request merged**
