### PR TITLE
Introduce `rustfmt`

### PR DESCRIPTION
**Pull request by tcharding**
(Includes the patch from #504, I pulled it out of this to merge faster)

Introduce `rustfmt` by doing:

- Copy the `rustfmt` config file from `rust-bitcoin`
- Prepare the codebase by adding `#[rustfmt::skip]` as needed and doing some manual format improvements.
- Run the formatter: `cargo +nightly fmt`
- Add formatting checks to CI and the pre-commit hook

Thanks in advance for doing the painful review on patch 3.

### CODE REVIEW

**Comment by tcharding** [comment]
WTF, the format change fail in CI is to a line that I cannot find in locally.

**Comment by tcharding** [comment]
> (A bit off-topic) @tcharding What do you think about: https://github.com/rust-lang/rustfmt/issues/5584 ?

I like the idea, not sure why the lad is so unequivocally against it. I don't think it helps us though since "existing" is unformatted the "desired" would never be triggered.

**Comment by dpc** [comment]
> I don't think it helps us though since "existing" is unformatted the "desired" would never be triggered.

That's a good point. It only helps projects that started formatted.

**Comment by tcharding** [comment]
Please note the recently added deprecated "since" strings are so long that they now go over multiple lines, its ugly but I figured since we remove them in a release anyway I'd leave them as is. Can change if required.

**Comment by apoelstra** [comment]
Will hold off on merging this for a bit since there are other PRs in flight and I think this'll conflict with everything.

**Comment by tcharding** [comment]
For me its better to just merge this one first please, I find these rustfmt PRs super boring to do where as I'm ok to rebase the others because they are much more interesting work. The only active PRs are my two I think.

**Comment by apoelstra** [comment]
Hah, fair enough. Merging now.

**Pull request merged**
