### PR TITLE
Automated daily update to rustc (to nightly-2024-09-10)

### PR DESCRIPTION
**Pull request by apoelstra**
Automated update to Github CI workflow `rust.yml` by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

### CODE REVIEW

**Review by tcharding — APPROVED** [review]
ACK 78d93b7ca5a6642e5bf482383067dd5a8a20bb19

**Comment by tcharding** [comment]
Bother, this is running the day before the one in `rust-bitcoin`.

**Comment by tcharding** [comment]
Oh no its not, they both run at midnight and one picked up "yesterdays" nightly and one pick up "tomorrows" nightly.

**Comment by apoelstra** [comment]
Lol. I guess we need to move it by an hour or two. I was also confused by this.

**Comment by apoelstra** [comment]
@tcharding this PR failed CI and should not have been merged.

**Comment by tcharding** [comment]
Sloppy, my bad.

**Pull request merged**
