### PR TITLE
bump version to 0.28.2

### PR DESCRIPTION
**Pull request by apoelstra**
Minor version which just adds some methods to various types.

### CODE REVIEW

**Comment by tcharding** [comment]
Needs lock file update man.

**Comment by apoelstra** [comment]
Ok, will run my local CI on my own PR :P.

But we need to start checking the lockfiles in CI here ... will wait for rust-bitcoin CI overhaul to settle out.

**Comment by apoelstra** [comment]
Ok shoud be good now.

**Review by Kixunil — APPROVED** [review]
ACK 1a162faf40d53f62076ea5865b318237effe2d61

**Comment by apoelstra** [comment]
Tagged and published.

**Pull request merged**
