### PR TITLE
Backport and bump 0.24.2

### PR DESCRIPTION
**Pull request by Kixunil**
I believe this is what tcharding meant by #558

### CODE REVIEW

**Review by apoelstra — APPROVED** [review]
utACK 5c6225e7b5062d83f18c67e3eaf13341e5bf6599

**Comment by Kixunil** [comment]
Uff, wasm is broken?

**Comment by tcharding** [comment]
> I believe this is what tcharding meant by https://github.com/rust-bitcoin/rust-secp256k1/pull/558

I'm confused, they are exactly the same code changes. The target branch did not exist when I created #588. I'm making a lot of mistakes this last few weeks but I don't see where my mistake was in this one. Not that it matters.

**Comment by tcharding** [comment]
Done by #559

**Pull request merged**
