### PR TITLE
Separated library into secp256k1 crate (high-level bindings) and secp256k1-sys crate (raw bindings).

### PR DESCRIPTION
**Pull request by alexreg**

### CODE REVIEW

**Comment by apoelstra** [comment]
Hi Alex, thanks for this! Let me fix Travis then I'll check this out.

**Comment by alexreg** [comment]
No problem.

**Comment by apoelstra** [comment]
Can you rebase on the latest commit? I only changed `.travis.yml` and I just added ` -- ` before `--release` in two places.

**Comment by tamasblummer** [comment]
@apoelstra is this too old to follow up ?

**Comment by apoelstra** [comment]
@tamasblummer Yeah, sorry.

**Pull request closed without merging**
