### PR TITLE
change --cfg=fuzzing to --cfg=secp256k1_fuzzing

### PR DESCRIPTION
**Pull request by apoelstra**
Companion PR to https://github.com/rust-bitcoin/rust-bitcoin/pull/1821

### CODE REVIEW

**Review by tcharding — APPROVED** [review]
ACK 0c1cbe707f83033c76b4fe47ecaa32842cda465f

**Review by Kixunil — APPROVED** [review]
ACK 0c1cbe707f83033c76b4fe47ecaa32842cda465f

**Comment by apoelstra** [comment]
Changed to use secp256k1_fuzz instead of secp256k1_fuzzing.

**Review by sanket1729 — APPROVED** [review]
ACK 9bdab895621c620f4eba0eb810b8895623748cd3

**Pull request merged**
