### PR TITLE
Fix broken benchmarks

### PR DESCRIPTION
**Pull request by elichai**
Currently the benchmarks in recovery weren't compiling.
I fixed and made travis compile them too.

I experimented with switching to criterion which looks pretty cool (works on stable, produces html plots, remembers last results to show you improvements/regressions etc.)
But dev-dependencies aren't allowed to be optional so this will break the tests on 1.22.0
https://github.com/rust-lang/cargo/issues/1596

(We could add it to the regular dependencies though, like @TheBlueMatt is doing with mutagen https://github.com/rust-bitcoin/rust-lightning/pull/453/files#r368478034 )

### CODE REVIEW

**Comment by real-or-random** [comment]
Thanks!

> I experimented with switching to criterion which looks pretty cool (works on stable, produces html plots, remembers last results to show you improvements/regressions etc.)

Do you something to share (e.g., a screenshot) to see what this is about? My first feeling is that nicer benchmarks would be more helpful upstream (but yeah, C...)

> But dev-dependencies aren't allowed to be optional so this will break the tests on 1.22.0
> [rust-lang/cargo#1596](https://github.com/rust-lang/cargo/issues/1596)
> 
> (We could add it to the regular dependencies though, like @TheBlueMatt is doing with mutagen https://github.com/rust-bitcoin/rust-lightning/pull/453/files#r368478034 )

Hm, it's indeed ugly. Not sure if we want this.

**Comment by elichai** [comment]
The "naive" output (from running `cargo bench`) is: https://i.imgur.com/Zq1nc78.png
(this is the result after I enable endomorphism)
But they also have HTML ouput, example: https://bheisler.github.io/criterion.rs/book/user_guide/html_report/Fibonacci2/Iterative/20/report/index.html
And CSV, and more things I haven't looked into yet ( https://bheisler.github.io/criterion.rs/book )

**Comment by elichai** [comment]
The no-std test was broken because of this PR: https://github.com/rust-lang/rust/pull/67502
they removed 2 lang items that were required before.

**Comment by apoelstra** [comment]
Can we make the "unstable" feature imply recovery and rand?

**Comment by elichai** [comment]
> Can we make the "unstable" feature imply recovery and rand?

Done. that also solved the conflicts :)

**Comment by apoelstra** [comment]
Travis is done. I dunno why it's not updating on the PR.

**Comment by real-or-random** [comment]
I've seen Travis status failing to update a few times in the past week (on upstream)...

Another question: Why are my review comments gone here in the PR? :/

**Comment by elichai** [comment]
That's really weird. I can see you reviewed it but I can't see the actual review/text

**Pull request merged**
